######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 11 14:48:02 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main_window.h model.h
SOURCES += main.cpp main_window.cpp model.cpp
RESOURCES += app.qrc
