######################################################################
# Automatically generated by qmake (3.0) Tue Mar 8 01:00:41 2016
######################################################################

TEMPLATE = app
TARGET = lights
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += main_window.h model.h
SOURCES += main.cpp main_window.cpp model.cpp
RESOURCES = app.qrc
