#############################################################################
# Makefile for building: lights
# Generated by qmake (3.0) (Qt 5.6.1)
# Project:  lights.pro
# Template: app
# Command: /home/alex/src/qtbase/bin/qmake -o Makefile lights.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../../../src/qtbase/include -I../../../src/qtbase/include/QtWidgets -I../../../src/qtbase/include/QtGui -I../../../src/qtbase/include/QtCore -I. -I../../../src/qtbase/mkspecs/linux-g++
QMAKE         = /home/alex/src/qtbase/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = lights1.0.0
DISTDIR = /home/alex/Dropbox/Projects/lights/.tmp/lights1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/alex/src/qtbase/lib
LIBS          = $(SUBLIBS) -L/home/alex/src/qtbase/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		main_window.cpp \
		model.cpp qrc_app.cpp \
		moc_main_window.cpp
OBJECTS       = main.o \
		main_window.o \
		model.o \
		qrc_app.o \
		moc_main_window.o
DIST          = ../../../src/qtbase/mkspecs/features/spec_pre.prf \
		../../../src/qtbase/mkspecs/common/unix.conf \
		../../../src/qtbase/mkspecs/common/linux.conf \
		../../../src/qtbase/mkspecs/common/sanitize.conf \
		../../../src/qtbase/mkspecs/common/gcc-base.conf \
		../../../src/qtbase/mkspecs/common/gcc-base-unix.conf \
		../../../src/qtbase/mkspecs/common/g++-base.conf \
		../../../src/qtbase/mkspecs/common/g++-unix.conf \
		../../../src/qtbase/mkspecs/qconfig.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_concurrent.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_core.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_core_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_dbus.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_gui.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_gui_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_network.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_network_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_opengl.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_sql.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_sql_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_xml.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_xml_private.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_ibusplatforminputcontextplugin.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_ibusplatforminputcontextplugin.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qconnmanbearer.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qconnmanbearer.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qevdevkeyboardplugin.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qevdevmouseplugin.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qevdevtabletplugin.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qevdevtouchplugin.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qgenericbearer.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qgif.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qgif.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qico.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qico.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qjpeg.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qlinuxfb.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qlinuxfb.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qminimal.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qminimal.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qnmbearer.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qnmbearer.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qoffscreen.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qsqlite.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qsqlpsql.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qsqlpsql.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qtuiotouchplugin.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../../src/qtbase/mkspecs/modules/qt_tool_moc.pri \
		../../../src/qtbase/mkspecs/modules/qt_tool_qdbuscpp2xml.pri \
		../../../src/qtbase/mkspecs/modules/qt_tool_qdbusxml2cpp.pri \
		../../../src/qtbase/mkspecs/modules/qt_tool_qlalr.pri \
		../../../src/qtbase/mkspecs/modules/qt_tool_rcc.pri \
		../../../src/qtbase/mkspecs/modules/qt_tool_syncqt.pri \
		../../../src/qtbase/mkspecs/modules/qt_tool_uic.pri \
		../../../src/qtbase/mkspecs/features/qt_functions.prf \
		../../../src/qtbase/mkspecs/features/qt_config.prf \
		../../../src/qtbase/mkspecs/linux-g++/qmake.conf \
		../../../src/qtbase/mkspecs/features/spec_post.prf \
		../../../src/qtbase/mkspecs/features/exclusive_builds.prf \
		../../../src/qtbase/mkspecs/features/default_pre.prf \
		../../../src/qtbase/mkspecs/features/resolve_config.prf \
		../../../src/qtbase/mkspecs/features/default_post.prf \
		../../../src/qtbase/mkspecs/features/warn_on.prf \
		../../../src/qtbase/mkspecs/features/qt.prf \
		../../../src/qtbase/mkspecs/features/resources.prf \
		../../../src/qtbase/mkspecs/features/moc.prf \
		../../../src/qtbase/mkspecs/features/unix/opengl.prf \
		../../../src/qtbase/mkspecs/features/uic.prf \
		../../../src/qtbase/mkspecs/features/unix/thread.prf \
		../../../src/qtbase/mkspecs/features/testcase_targets.prf \
		../../../src/qtbase/mkspecs/features/exceptions.prf \
		../../../src/qtbase/mkspecs/features/yacc.prf \
		../../../src/qtbase/mkspecs/features/lex.prf \
		lights.pro main_window.h \
		model.h main.cpp \
		main_window.cpp \
		model.cpp
QMAKE_TARGET  = lights
DESTDIR       = 
TARGET        = lights


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: lights.pro ../../../src/qtbase/mkspecs/linux-g++/qmake.conf ../../../src/qtbase/mkspecs/features/spec_pre.prf \
		../../../src/qtbase/mkspecs/common/unix.conf \
		../../../src/qtbase/mkspecs/common/linux.conf \
		../../../src/qtbase/mkspecs/common/sanitize.conf \
		../../../src/qtbase/mkspecs/common/gcc-base.conf \
		../../../src/qtbase/mkspecs/common/gcc-base-unix.conf \
		../../../src/qtbase/mkspecs/common/g++-base.conf \
		../../../src/qtbase/mkspecs/common/g++-unix.conf \
		../../../src/qtbase/mkspecs/qconfig.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_concurrent.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_core.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_core_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_dbus.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_gui.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_gui_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_network.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_network_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_opengl.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_sql.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_sql_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_xml.pri \
		../../../src/qtbase/mkspecs/modules/qt_lib_xml_private.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_ibusplatforminputcontextplugin.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_ibusplatforminputcontextplugin.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qconnmanbearer.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qconnmanbearer.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qevdevkeyboardplugin.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qevdevmouseplugin.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qevdevtabletplugin.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qevdevtouchplugin.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qgenericbearer.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qgif.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qgif.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qico.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qico.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qjpeg.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qlinuxfb.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qlinuxfb.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qminimal.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qminimal.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qnmbearer.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qnmbearer.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qoffscreen.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qsqlite.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qsqlpsql.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qsqlpsql.pri \
		../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qtuiotouchplugin.pri \
		../../../src/qtbase/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../../src/qtbase/mkspecs/modules/qt_tool_moc.pri \
		../../../src/qtbase/mkspecs/modules/qt_tool_qdbuscpp2xml.pri \
		../../../src/qtbase/mkspecs/modules/qt_tool_qdbusxml2cpp.pri \
		../../../src/qtbase/mkspecs/modules/qt_tool_qlalr.pri \
		../../../src/qtbase/mkspecs/modules/qt_tool_rcc.pri \
		../../../src/qtbase/mkspecs/modules/qt_tool_syncqt.pri \
		../../../src/qtbase/mkspecs/modules/qt_tool_uic.pri \
		../../../src/qtbase/mkspecs/features/qt_functions.prf \
		../../../src/qtbase/mkspecs/features/qt_config.prf \
		../../../src/qtbase/mkspecs/linux-g++/qmake.conf \
		../../../src/qtbase/mkspecs/features/spec_post.prf \
		../../../src/qtbase/mkspecs/features/exclusive_builds.prf \
		../../../src/qtbase/mkspecs/features/default_pre.prf \
		../../../src/qtbase/mkspecs/features/resolve_config.prf \
		../../../src/qtbase/mkspecs/features/default_post.prf \
		../../../src/qtbase/mkspecs/features/warn_on.prf \
		../../../src/qtbase/mkspecs/features/qt.prf \
		../../../src/qtbase/mkspecs/features/resources.prf \
		../../../src/qtbase/mkspecs/features/moc.prf \
		../../../src/qtbase/mkspecs/features/unix/opengl.prf \
		../../../src/qtbase/mkspecs/features/uic.prf \
		../../../src/qtbase/mkspecs/features/unix/thread.prf \
		../../../src/qtbase/mkspecs/features/testcase_targets.prf \
		../../../src/qtbase/mkspecs/features/exceptions.prf \
		../../../src/qtbase/mkspecs/features/yacc.prf \
		../../../src/qtbase/mkspecs/features/lex.prf \
		lights.pro \
		app.qrc \
		../../../src/qtbase/lib/libQt5Widgets.prl \
		../../../src/qtbase/lib/libQt5Gui.prl \
		../../../src/qtbase/lib/libQt5Core.prl
	$(QMAKE) -o Makefile lights.pro
../../../src/qtbase/mkspecs/features/spec_pre.prf:
../../../src/qtbase/mkspecs/common/unix.conf:
../../../src/qtbase/mkspecs/common/linux.conf:
../../../src/qtbase/mkspecs/common/sanitize.conf:
../../../src/qtbase/mkspecs/common/gcc-base.conf:
../../../src/qtbase/mkspecs/common/gcc-base-unix.conf:
../../../src/qtbase/mkspecs/common/g++-base.conf:
../../../src/qtbase/mkspecs/common/g++-unix.conf:
../../../src/qtbase/mkspecs/qconfig.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_concurrent.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_core.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_core_private.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_dbus.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_dbus_private.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_gui.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_gui_private.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_network.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_network_private.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_opengl.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_opengl_private.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_openglextensions.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_printsupport.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_sql.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_sql_private.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_testlib.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_testlib_private.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_widgets.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_widgets_private.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_xml.pri:
../../../src/qtbase/mkspecs/modules/qt_lib_xml_private.pri:
../../../src/qtbase/mkspecs/modules-inst/qt_plugin_ibusplatforminputcontextplugin.pri:
../../../src/qtbase/mkspecs/modules/qt_plugin_ibusplatforminputcontextplugin.pri:
../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qconnmanbearer.pri:
../../../src/qtbase/mkspecs/modules/qt_plugin_qconnmanbearer.pri:
../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qevdevkeyboardplugin.pri:
../../../src/qtbase/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri:
../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qevdevmouseplugin.pri:
../../../src/qtbase/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri:
../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qevdevtabletplugin.pri:
../../../src/qtbase/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri:
../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qevdevtouchplugin.pri:
../../../src/qtbase/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri:
../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qgenericbearer.pri:
../../../src/qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qgif.pri:
../../../src/qtbase/mkspecs/modules/qt_plugin_qgif.pri:
../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qico.pri:
../../../src/qtbase/mkspecs/modules/qt_plugin_qico.pri:
../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qjpeg.pri:
../../../src/qtbase/mkspecs/modules/qt_plugin_qjpeg.pri:
../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qlinuxfb.pri:
../../../src/qtbase/mkspecs/modules/qt_plugin_qlinuxfb.pri:
../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qminimal.pri:
../../../src/qtbase/mkspecs/modules/qt_plugin_qminimal.pri:
../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qnmbearer.pri:
../../../src/qtbase/mkspecs/modules/qt_plugin_qnmbearer.pri:
../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qoffscreen.pri:
../../../src/qtbase/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qsqlite.pri:
../../../src/qtbase/mkspecs/modules/qt_plugin_qsqlite.pri:
../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qsqlpsql.pri:
../../../src/qtbase/mkspecs/modules/qt_plugin_qsqlpsql.pri:
../../../src/qtbase/mkspecs/modules-inst/qt_plugin_qtuiotouchplugin.pri:
../../../src/qtbase/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../../src/qtbase/mkspecs/modules/qt_tool_moc.pri:
../../../src/qtbase/mkspecs/modules/qt_tool_qdbuscpp2xml.pri:
../../../src/qtbase/mkspecs/modules/qt_tool_qdbusxml2cpp.pri:
../../../src/qtbase/mkspecs/modules/qt_tool_qlalr.pri:
../../../src/qtbase/mkspecs/modules/qt_tool_rcc.pri:
../../../src/qtbase/mkspecs/modules/qt_tool_syncqt.pri:
../../../src/qtbase/mkspecs/modules/qt_tool_uic.pri:
../../../src/qtbase/mkspecs/features/qt_functions.prf:
../../../src/qtbase/mkspecs/features/qt_config.prf:
../../../src/qtbase/mkspecs/linux-g++/qmake.conf:
../../../src/qtbase/mkspecs/features/spec_post.prf:
../../../src/qtbase/mkspecs/features/exclusive_builds.prf:
../../../src/qtbase/mkspecs/features/default_pre.prf:
../../../src/qtbase/mkspecs/features/resolve_config.prf:
../../../src/qtbase/mkspecs/features/default_post.prf:
../../../src/qtbase/mkspecs/features/warn_on.prf:
../../../src/qtbase/mkspecs/features/qt.prf:
../../../src/qtbase/mkspecs/features/resources.prf:
../../../src/qtbase/mkspecs/features/moc.prf:
../../../src/qtbase/mkspecs/features/unix/opengl.prf:
../../../src/qtbase/mkspecs/features/uic.prf:
../../../src/qtbase/mkspecs/features/unix/thread.prf:
../../../src/qtbase/mkspecs/features/testcase_targets.prf:
../../../src/qtbase/mkspecs/features/exceptions.prf:
../../../src/qtbase/mkspecs/features/yacc.prf:
../../../src/qtbase/mkspecs/features/lex.prf:
lights.pro:
app.qrc:
../../../src/qtbase/lib/libQt5Widgets.prl:
../../../src/qtbase/lib/libQt5Gui.prl:
../../../src/qtbase/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile lights.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents app.qrc $(DISTDIR)/
	$(COPY_FILE) --parents main_window.h model.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp main_window.cpp model.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) /home/alex/Dropbox/Projects/lights/uic_wrapper.sh /home/alex/Dropbox/Projects/lights/uic_wrapper.sh
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_app.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_app.cpp
qrc_app.cpp: app.qrc \
		images/save.png \
		images/saveAs.png \
		images/open.png \
		images/plus.png \
		images/new.png
	/home/alex/src/qtbase/bin/rcc -name app app.qrc -o qrc_app.cpp

compiler_moc_header_make_all: moc_main_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_main_window.cpp
moc_main_window.cpp: ../../../src/qtbase/include/QtWidgets/QMainWindow \
		../../../src/qtbase/include/QtWidgets/qmainwindow.h \
		../../../src/qtbase/src/widgets/widgets/qmainwindow.h \
		../../../src/qtbase/include/QtWidgets/qwidget.h \
		../../../src/qtbase/src/widgets/kernel/qwidget.h \
		../../../src/qtbase/include/QtGui/qwindowdefs.h \
		../../../src/qtbase/src/gui/kernel/qwindowdefs.h \
		../../../src/qtbase/include/QtCore/qglobal.h \
		../../../src/qtbase/src/corelib/global/qglobal.h \
		../../../src/qtbase/include/QtCore/qconfig.h \
		../../../src/qtbase/src/corelib/global/qconfig.h \
		../../../src/qtbase/include/QtCore/qfeatures.h \
		../../../src/qtbase/src/corelib/global/qfeatures.h \
		../../../src/qtbase/include/QtCore/qsystemdetection.h \
		../../../src/qtbase/src/corelib/global/qsystemdetection.h \
		../../../src/qtbase/include/QtCore/qprocessordetection.h \
		../../../src/qtbase/src/corelib/global/qprocessordetection.h \
		../../../src/qtbase/include/QtCore/qcompilerdetection.h \
		../../../src/qtbase/src/corelib/global/qcompilerdetection.h \
		../../../src/qtbase/include/QtCore/qtypeinfo.h \
		../../../src/qtbase/src/corelib/global/qtypeinfo.h \
		../../../src/qtbase/include/QtCore/qtypetraits.h \
		../../../src/qtbase/src/corelib/global/qtypetraits.h \
		../../../src/qtbase/include/QtCore/qisenum.h \
		../../../src/qtbase/src/corelib/global/qisenum.h \
		../../../src/qtbase/include/QtCore/qsysinfo.h \
		../../../src/qtbase/src/corelib/global/qsysinfo.h \
		../../../src/qtbase/include/QtCore/qlogging.h \
		../../../src/qtbase/src/corelib/global/qlogging.h \
		../../../src/qtbase/include/QtCore/qflags.h \
		../../../src/qtbase/src/corelib/global/qflags.h \
		../../../src/qtbase/include/QtCore/qatomic.h \
		../../../src/qtbase/src/corelib/thread/qatomic.h \
		../../../src/qtbase/include/QtCore/qbasicatomic.h \
		../../../src/qtbase/src/corelib/thread/qbasicatomic.h \
		../../../src/qtbase/include/QtCore/qatomic_bootstrap.h \
		../../../src/qtbase/src/corelib/arch/qatomic_bootstrap.h \
		../../../src/qtbase/include/QtCore/qgenericatomic.h \
		../../../src/qtbase/src/corelib/thread/qgenericatomic.h \
		../../../src/qtbase/include/QtCore/qatomic_cxx11.h \
		../../../src/qtbase/src/corelib/arch/qatomic_cxx11.h \
		../../../src/qtbase/include/QtCore/qatomic_gcc.h \
		../../../src/qtbase/src/corelib/arch/qatomic_gcc.h \
		../../../src/qtbase/include/QtCore/qatomic_msvc.h \
		../../../src/qtbase/src/corelib/arch/qatomic_msvc.h \
		../../../src/qtbase/include/QtCore/qatomic_armv7.h \
		../../../src/qtbase/src/corelib/arch/qatomic_armv7.h \
		../../../src/qtbase/include/QtCore/qatomic_armv6.h \
		../../../src/qtbase/src/corelib/arch/qatomic_armv6.h \
		../../../src/qtbase/include/QtCore/qatomic_armv5.h \
		../../../src/qtbase/src/corelib/arch/qatomic_armv5.h \
		../../../src/qtbase/include/QtCore/qatomic_ia64.h \
		../../../src/qtbase/src/corelib/arch/qatomic_ia64.h \
		../../../src/qtbase/include/QtCore/qatomic_x86.h \
		../../../src/qtbase/src/corelib/arch/qatomic_x86.h \
		../../../src/qtbase/include/QtCore/qatomic_unix.h \
		../../../src/qtbase/src/corelib/arch/qatomic_unix.h \
		../../../src/qtbase/include/QtCore/qglobalstatic.h \
		../../../src/qtbase/src/corelib/global/qglobalstatic.h \
		../../../src/qtbase/include/QtCore/qmutex.h \
		../../../src/qtbase/src/corelib/thread/qmutex.h \
		../../../src/qtbase/include/QtCore/qnumeric.h \
		../../../src/qtbase/src/corelib/global/qnumeric.h \
		../../../src/qtbase/include/QtCore/qversiontagging.h \
		../../../src/qtbase/src/corelib/global/qversiontagging.h \
		../../../src/qtbase/include/QtCore/qobjectdefs.h \
		../../../src/qtbase/src/corelib/kernel/qobjectdefs.h \
		../../../src/qtbase/include/QtCore/qnamespace.h \
		../../../src/qtbase/src/corelib/global/qnamespace.h \
		../../../src/qtbase/include/QtCore/qobjectdefs_impl.h \
		../../../src/qtbase/src/corelib/kernel/qobjectdefs_impl.h \
		../../../src/qtbase/include/QtGui/qwindowdefs_win.h \
		../../../src/qtbase/src/gui/kernel/qwindowdefs_win.h \
		../../../src/qtbase/include/QtCore/qobject.h \
		../../../src/qtbase/src/corelib/kernel/qobject.h \
		../../../src/qtbase/include/QtCore/qstring.h \
		../../../src/qtbase/src/corelib/tools/qstring.h \
		../../../src/qtbase/include/QtCore/qchar.h \
		../../../src/qtbase/src/corelib/tools/qchar.h \
		../../../src/qtbase/include/QtCore/qbytearray.h \
		../../../src/qtbase/src/corelib/tools/qbytearray.h \
		../../../src/qtbase/include/QtCore/qrefcount.h \
		../../../src/qtbase/src/corelib/tools/qrefcount.h \
		../../../src/qtbase/include/QtCore/qarraydata.h \
		../../../src/qtbase/src/corelib/tools/qarraydata.h \
		../../../src/qtbase/include/QtCore/qstringbuilder.h \
		../../../src/qtbase/src/corelib/tools/qstringbuilder.h \
		../../../src/qtbase/include/QtCore/qlist.h \
		../../../src/qtbase/src/corelib/tools/qlist.h \
		../../../src/qtbase/include/QtCore/qalgorithms.h \
		../../../src/qtbase/src/corelib/tools/qalgorithms.h \
		../../../src/qtbase/include/QtCore/qiterator.h \
		../../../src/qtbase/src/corelib/tools/qiterator.h \
		../../../src/qtbase/include/QtCore/qhashfunctions.h \
		../../../src/qtbase/src/corelib/tools/qhashfunctions.h \
		../../../src/qtbase/include/QtCore/qpair.h \
		../../../src/qtbase/src/corelib/tools/qpair.h \
		../../../src/qtbase/include/QtCore/qbytearraylist.h \
		../../../src/qtbase/src/corelib/tools/qbytearraylist.h \
		../../../src/qtbase/include/QtCore/qstringlist.h \
		../../../src/qtbase/src/corelib/tools/qstringlist.h \
		../../../src/qtbase/include/QtCore/qregexp.h \
		../../../src/qtbase/src/corelib/tools/qregexp.h \
		../../../src/qtbase/include/QtCore/qstringmatcher.h \
		../../../src/qtbase/src/corelib/tools/qstringmatcher.h \
		../../../src/qtbase/include/QtCore/qcoreevent.h \
		../../../src/qtbase/src/corelib/kernel/qcoreevent.h \
		../../../src/qtbase/include/QtCore/qscopedpointer.h \
		../../../src/qtbase/src/corelib/tools/qscopedpointer.h \
		../../../src/qtbase/include/QtCore/qmetatype.h \
		../../../src/qtbase/src/corelib/kernel/qmetatype.h \
		../../../src/qtbase/include/QtCore/qvarlengtharray.h \
		../../../src/qtbase/src/corelib/tools/qvarlengtharray.h \
		../../../src/qtbase/include/QtCore/qcontainerfwd.h \
		../../../src/qtbase/src/corelib/tools/qcontainerfwd.h \
		../../../src/qtbase/include/QtCore/qobject_impl.h \
		../../../src/qtbase/src/corelib/kernel/qobject_impl.h \
		../../../src/qtbase/include/QtCore/qmargins.h \
		../../../src/qtbase/src/corelib/tools/qmargins.h \
		../../../src/qtbase/include/QtGui/qpaintdevice.h \
		../../../src/qtbase/src/gui/painting/qpaintdevice.h \
		../../../src/qtbase/include/QtCore/qrect.h \
		../../../src/qtbase/src/corelib/tools/qrect.h \
		../../../src/qtbase/include/QtCore/qsize.h \
		../../../src/qtbase/src/corelib/tools/qsize.h \
		../../../src/qtbase/include/QtCore/qpoint.h \
		../../../src/qtbase/src/corelib/tools/qpoint.h \
		../../../src/qtbase/include/QtGui/qpalette.h \
		../../../src/qtbase/src/gui/kernel/qpalette.h \
		../../../src/qtbase/include/QtGui/qcolor.h \
		../../../src/qtbase/src/gui/painting/qcolor.h \
		../../../src/qtbase/include/QtGui/qrgb.h \
		../../../src/qtbase/src/gui/painting/qrgb.h \
		../../../src/qtbase/include/QtGui/qrgba64.h \
		../../../src/qtbase/src/gui/painting/qrgba64.h \
		../../../src/qtbase/include/QtGui/qbrush.h \
		../../../src/qtbase/src/gui/painting/qbrush.h \
		../../../src/qtbase/include/QtCore/qvector.h \
		../../../src/qtbase/src/corelib/tools/qvector.h \
		../../../src/qtbase/include/QtGui/qmatrix.h \
		../../../src/qtbase/src/gui/painting/qmatrix.h \
		../../../src/qtbase/include/QtGui/qpolygon.h \
		../../../src/qtbase/src/gui/painting/qpolygon.h \
		../../../src/qtbase/include/QtGui/qregion.h \
		../../../src/qtbase/src/gui/painting/qregion.h \
		../../../src/qtbase/include/QtCore/qdatastream.h \
		../../../src/qtbase/src/corelib/io/qdatastream.h \
		../../../src/qtbase/include/QtCore/qiodevice.h \
		../../../src/qtbase/src/corelib/io/qiodevice.h \
		../../../src/qtbase/include/QtCore/qline.h \
		../../../src/qtbase/src/corelib/tools/qline.h \
		../../../src/qtbase/include/QtGui/qtransform.h \
		../../../src/qtbase/src/gui/painting/qtransform.h \
		../../../src/qtbase/include/QtGui/qpainterpath.h \
		../../../src/qtbase/src/gui/painting/qpainterpath.h \
		../../../src/qtbase/include/QtGui/qimage.h \
		../../../src/qtbase/src/gui/image/qimage.h \
		../../../src/qtbase/include/QtGui/qpixelformat.h \
		../../../src/qtbase/src/gui/kernel/qpixelformat.h \
		../../../src/qtbase/include/QtGui/qpixmap.h \
		../../../src/qtbase/src/gui/image/qpixmap.h \
		../../../src/qtbase/include/QtCore/qsharedpointer.h \
		../../../src/qtbase/src/corelib/tools/qsharedpointer.h \
		../../../src/qtbase/include/QtCore/qshareddata.h \
		../../../src/qtbase/src/corelib/tools/qshareddata.h \
		../../../src/qtbase/include/QtCore/qhash.h \
		../../../src/qtbase/src/corelib/tools/qhash.h \
		../../../src/qtbase/include/QtCore/qsharedpointer_impl.h \
		../../../src/qtbase/src/corelib/tools/qsharedpointer_impl.h \
		../../../src/qtbase/include/QtGui/qfont.h \
		../../../src/qtbase/src/gui/text/qfont.h \
		../../../src/qtbase/include/QtGui/qfontmetrics.h \
		../../../src/qtbase/src/gui/text/qfontmetrics.h \
		../../../src/qtbase/include/QtGui/qfontinfo.h \
		../../../src/qtbase/src/gui/text/qfontinfo.h \
		../../../src/qtbase/include/QtWidgets/qsizepolicy.h \
		../../../src/qtbase/src/widgets/kernel/qsizepolicy.h \
		../../../src/qtbase/include/QtGui/qcursor.h \
		../../../src/qtbase/src/gui/kernel/qcursor.h \
		../../../src/qtbase/include/QtGui/qkeysequence.h \
		../../../src/qtbase/src/gui/kernel/qkeysequence.h \
		../../../src/qtbase/include/QtGui/qevent.h \
		../../../src/qtbase/src/gui/kernel/qevent.h \
		../../../src/qtbase/include/QtCore/qvariant.h \
		../../../src/qtbase/src/corelib/kernel/qvariant.h \
		../../../src/qtbase/include/QtCore/qmap.h \
		../../../src/qtbase/src/corelib/tools/qmap.h \
		../../../src/qtbase/include/QtCore/qdebug.h \
		../../../src/qtbase/src/corelib/io/qdebug.h \
		../../../src/qtbase/include/QtCore/qtextstream.h \
		../../../src/qtbase/src/corelib/io/qtextstream.h \
		../../../src/qtbase/include/QtCore/qlocale.h \
		../../../src/qtbase/src/corelib/tools/qlocale.h \
		../../../src/qtbase/include/QtCore/qset.h \
		../../../src/qtbase/src/corelib/tools/qset.h \
		../../../src/qtbase/include/QtCore/qcontiguouscache.h \
		../../../src/qtbase/src/corelib/tools/qcontiguouscache.h \
		../../../src/qtbase/include/QtCore/qurl.h \
		../../../src/qtbase/src/corelib/io/qurl.h \
		../../../src/qtbase/include/QtCore/qurlquery.h \
		../../../src/qtbase/src/corelib/io/qurlquery.h \
		../../../src/qtbase/include/QtCore/qfile.h \
		../../../src/qtbase/src/corelib/io/qfile.h \
		../../../src/qtbase/include/QtCore/qfiledevice.h \
		../../../src/qtbase/src/corelib/io/qfiledevice.h \
		../../../src/qtbase/include/QtGui/qvector2d.h \
		../../../src/qtbase/src/gui/math3d/qvector2d.h \
		../../../src/qtbase/include/QtGui/qtouchdevice.h \
		../../../src/qtbase/src/gui/kernel/qtouchdevice.h \
		../../../src/qtbase/include/QtWidgets/qtabwidget.h \
		../../../src/qtbase/src/widgets/widgets/qtabwidget.h \
		../../../src/qtbase/include/QtGui/qicon.h \
		../../../src/qtbase/src/gui/image/qicon.h \
		model.h \
		main_window.h
	/home/alex/src/qtbase/bin/moc $(DEFINES) -I/home/alex/src/qtbase/mkspecs/linux-g++ -I/home/alex/Dropbox/Projects/lights -I/home/alex/Dropbox/Projects/lights -I/home/alex/src/qtbase/include -I/home/alex/src/qtbase/include/QtWidgets -I/home/alex/src/qtbase/include/QtGui -I/home/alex/src/qtbase/include/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include main_window.h -o moc_main_window.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../../src/qtbase/include/QtWidgets/QApplication \
		../../../src/qtbase/include/QtWidgets/qapplication.h \
		../../../src/qtbase/src/widgets/kernel/qapplication.h \
		../../../src/qtbase/include/QtCore/qcoreapplication.h \
		../../../src/qtbase/src/corelib/kernel/qcoreapplication.h \
		../../../src/qtbase/include/QtCore/qglobal.h \
		../../../src/qtbase/src/corelib/global/qglobal.h \
		../../../src/qtbase/include/QtCore/qconfig.h \
		../../../src/qtbase/src/corelib/global/qconfig.h \
		../../../src/qtbase/include/QtCore/qfeatures.h \
		../../../src/qtbase/src/corelib/global/qfeatures.h \
		../../../src/qtbase/include/QtCore/qsystemdetection.h \
		../../../src/qtbase/src/corelib/global/qsystemdetection.h \
		../../../src/qtbase/include/QtCore/qprocessordetection.h \
		../../../src/qtbase/src/corelib/global/qprocessordetection.h \
		../../../src/qtbase/include/QtCore/qcompilerdetection.h \
		../../../src/qtbase/src/corelib/global/qcompilerdetection.h \
		../../../src/qtbase/include/QtCore/qtypeinfo.h \
		../../../src/qtbase/src/corelib/global/qtypeinfo.h \
		../../../src/qtbase/include/QtCore/qtypetraits.h \
		../../../src/qtbase/src/corelib/global/qtypetraits.h \
		../../../src/qtbase/include/QtCore/qisenum.h \
		../../../src/qtbase/src/corelib/global/qisenum.h \
		../../../src/qtbase/include/QtCore/qsysinfo.h \
		../../../src/qtbase/src/corelib/global/qsysinfo.h \
		../../../src/qtbase/include/QtCore/qlogging.h \
		../../../src/qtbase/src/corelib/global/qlogging.h \
		../../../src/qtbase/include/QtCore/qflags.h \
		../../../src/qtbase/src/corelib/global/qflags.h \
		../../../src/qtbase/include/QtCore/qatomic.h \
		../../../src/qtbase/src/corelib/thread/qatomic.h \
		../../../src/qtbase/include/QtCore/qbasicatomic.h \
		../../../src/qtbase/src/corelib/thread/qbasicatomic.h \
		../../../src/qtbase/include/QtCore/qatomic_bootstrap.h \
		../../../src/qtbase/src/corelib/arch/qatomic_bootstrap.h \
		../../../src/qtbase/include/QtCore/qgenericatomic.h \
		../../../src/qtbase/src/corelib/thread/qgenericatomic.h \
		../../../src/qtbase/include/QtCore/qatomic_cxx11.h \
		../../../src/qtbase/src/corelib/arch/qatomic_cxx11.h \
		../../../src/qtbase/include/QtCore/qatomic_gcc.h \
		../../../src/qtbase/src/corelib/arch/qatomic_gcc.h \
		../../../src/qtbase/include/QtCore/qatomic_msvc.h \
		../../../src/qtbase/src/corelib/arch/qatomic_msvc.h \
		../../../src/qtbase/include/QtCore/qatomic_armv7.h \
		../../../src/qtbase/src/corelib/arch/qatomic_armv7.h \
		../../../src/qtbase/include/QtCore/qatomic_armv6.h \
		../../../src/qtbase/src/corelib/arch/qatomic_armv6.h \
		../../../src/qtbase/include/QtCore/qatomic_armv5.h \
		../../../src/qtbase/src/corelib/arch/qatomic_armv5.h \
		../../../src/qtbase/include/QtCore/qatomic_ia64.h \
		../../../src/qtbase/src/corelib/arch/qatomic_ia64.h \
		../../../src/qtbase/include/QtCore/qatomic_x86.h \
		../../../src/qtbase/src/corelib/arch/qatomic_x86.h \
		../../../src/qtbase/include/QtCore/qatomic_unix.h \
		../../../src/qtbase/src/corelib/arch/qatomic_unix.h \
		../../../src/qtbase/include/QtCore/qglobalstatic.h \
		../../../src/qtbase/src/corelib/global/qglobalstatic.h \
		../../../src/qtbase/include/QtCore/qmutex.h \
		../../../src/qtbase/src/corelib/thread/qmutex.h \
		../../../src/qtbase/include/QtCore/qnumeric.h \
		../../../src/qtbase/src/corelib/global/qnumeric.h \
		../../../src/qtbase/include/QtCore/qversiontagging.h \
		../../../src/qtbase/src/corelib/global/qversiontagging.h \
		../../../src/qtbase/include/QtCore/qstring.h \
		../../../src/qtbase/src/corelib/tools/qstring.h \
		../../../src/qtbase/include/QtCore/qchar.h \
		../../../src/qtbase/src/corelib/tools/qchar.h \
		../../../src/qtbase/include/QtCore/qbytearray.h \
		../../../src/qtbase/src/corelib/tools/qbytearray.h \
		../../../src/qtbase/include/QtCore/qrefcount.h \
		../../../src/qtbase/src/corelib/tools/qrefcount.h \
		../../../src/qtbase/include/QtCore/qnamespace.h \
		../../../src/qtbase/src/corelib/global/qnamespace.h \
		../../../src/qtbase/include/QtCore/qarraydata.h \
		../../../src/qtbase/src/corelib/tools/qarraydata.h \
		../../../src/qtbase/include/QtCore/qstringbuilder.h \
		../../../src/qtbase/src/corelib/tools/qstringbuilder.h \
		../../../src/qtbase/include/QtCore/qobject.h \
		../../../src/qtbase/src/corelib/kernel/qobject.h \
		../../../src/qtbase/include/QtCore/qobjectdefs.h \
		../../../src/qtbase/src/corelib/kernel/qobjectdefs.h \
		../../../src/qtbase/include/QtCore/qobjectdefs_impl.h \
		../../../src/qtbase/src/corelib/kernel/qobjectdefs_impl.h \
		../../../src/qtbase/include/QtCore/qlist.h \
		../../../src/qtbase/src/corelib/tools/qlist.h \
		../../../src/qtbase/include/QtCore/qalgorithms.h \
		../../../src/qtbase/src/corelib/tools/qalgorithms.h \
		../../../src/qtbase/include/QtCore/qiterator.h \
		../../../src/qtbase/src/corelib/tools/qiterator.h \
		../../../src/qtbase/include/QtCore/qhashfunctions.h \
		../../../src/qtbase/src/corelib/tools/qhashfunctions.h \
		../../../src/qtbase/include/QtCore/qpair.h \
		../../../src/qtbase/src/corelib/tools/qpair.h \
		../../../src/qtbase/include/QtCore/qbytearraylist.h \
		../../../src/qtbase/src/corelib/tools/qbytearraylist.h \
		../../../src/qtbase/include/QtCore/qstringlist.h \
		../../../src/qtbase/src/corelib/tools/qstringlist.h \
		../../../src/qtbase/include/QtCore/qregexp.h \
		../../../src/qtbase/src/corelib/tools/qregexp.h \
		../../../src/qtbase/include/QtCore/qstringmatcher.h \
		../../../src/qtbase/src/corelib/tools/qstringmatcher.h \
		../../../src/qtbase/include/QtCore/qcoreevent.h \
		../../../src/qtbase/src/corelib/kernel/qcoreevent.h \
		../../../src/qtbase/include/QtCore/qscopedpointer.h \
		../../../src/qtbase/src/corelib/tools/qscopedpointer.h \
		../../../src/qtbase/include/QtCore/qmetatype.h \
		../../../src/qtbase/src/corelib/kernel/qmetatype.h \
		../../../src/qtbase/include/QtCore/qvarlengtharray.h \
		../../../src/qtbase/src/corelib/tools/qvarlengtharray.h \
		../../../src/qtbase/include/QtCore/qcontainerfwd.h \
		../../../src/qtbase/src/corelib/tools/qcontainerfwd.h \
		../../../src/qtbase/include/QtCore/qobject_impl.h \
		../../../src/qtbase/src/corelib/kernel/qobject_impl.h \
		../../../src/qtbase/include/QtCore/qeventloop.h \
		../../../src/qtbase/src/corelib/kernel/qeventloop.h \
		../../../src/qtbase/include/QtGui/qwindowdefs.h \
		../../../src/qtbase/src/gui/kernel/qwindowdefs.h \
		../../../src/qtbase/include/QtGui/qwindowdefs_win.h \
		../../../src/qtbase/src/gui/kernel/qwindowdefs_win.h \
		../../../src/qtbase/include/QtCore/qpoint.h \
		../../../src/qtbase/src/corelib/tools/qpoint.h \
		../../../src/qtbase/include/QtCore/qsize.h \
		../../../src/qtbase/src/corelib/tools/qsize.h \
		../../../src/qtbase/include/QtGui/qcursor.h \
		../../../src/qtbase/src/gui/kernel/qcursor.h \
		../../../src/qtbase/include/QtWidgets/qdesktopwidget.h \
		../../../src/qtbase/src/widgets/kernel/qdesktopwidget.h \
		../../../src/qtbase/include/QtWidgets/qwidget.h \
		../../../src/qtbase/src/widgets/kernel/qwidget.h \
		../../../src/qtbase/include/QtCore/qmargins.h \
		../../../src/qtbase/src/corelib/tools/qmargins.h \
		../../../src/qtbase/include/QtGui/qpaintdevice.h \
		../../../src/qtbase/src/gui/painting/qpaintdevice.h \
		../../../src/qtbase/include/QtCore/qrect.h \
		../../../src/qtbase/src/corelib/tools/qrect.h \
		../../../src/qtbase/include/QtGui/qpalette.h \
		../../../src/qtbase/src/gui/kernel/qpalette.h \
		../../../src/qtbase/include/QtGui/qcolor.h \
		../../../src/qtbase/src/gui/painting/qcolor.h \
		../../../src/qtbase/include/QtGui/qrgb.h \
		../../../src/qtbase/src/gui/painting/qrgb.h \
		../../../src/qtbase/include/QtGui/qrgba64.h \
		../../../src/qtbase/src/gui/painting/qrgba64.h \
		../../../src/qtbase/include/QtGui/qbrush.h \
		../../../src/qtbase/src/gui/painting/qbrush.h \
		../../../src/qtbase/include/QtCore/qvector.h \
		../../../src/qtbase/src/corelib/tools/qvector.h \
		../../../src/qtbase/include/QtGui/qmatrix.h \
		../../../src/qtbase/src/gui/painting/qmatrix.h \
		../../../src/qtbase/include/QtGui/qpolygon.h \
		../../../src/qtbase/src/gui/painting/qpolygon.h \
		../../../src/qtbase/include/QtGui/qregion.h \
		../../../src/qtbase/src/gui/painting/qregion.h \
		../../../src/qtbase/include/QtCore/qdatastream.h \
		../../../src/qtbase/src/corelib/io/qdatastream.h \
		../../../src/qtbase/include/QtCore/qiodevice.h \
		../../../src/qtbase/src/corelib/io/qiodevice.h \
		../../../src/qtbase/include/QtCore/qline.h \
		../../../src/qtbase/src/corelib/tools/qline.h \
		../../../src/qtbase/include/QtGui/qtransform.h \
		../../../src/qtbase/src/gui/painting/qtransform.h \
		../../../src/qtbase/include/QtGui/qpainterpath.h \
		../../../src/qtbase/src/gui/painting/qpainterpath.h \
		../../../src/qtbase/include/QtGui/qimage.h \
		../../../src/qtbase/src/gui/image/qimage.h \
		../../../src/qtbase/include/QtGui/qpixelformat.h \
		../../../src/qtbase/src/gui/kernel/qpixelformat.h \
		../../../src/qtbase/include/QtGui/qpixmap.h \
		../../../src/qtbase/src/gui/image/qpixmap.h \
		../../../src/qtbase/include/QtCore/qsharedpointer.h \
		../../../src/qtbase/src/corelib/tools/qsharedpointer.h \
		../../../src/qtbase/include/QtCore/qshareddata.h \
		../../../src/qtbase/src/corelib/tools/qshareddata.h \
		../../../src/qtbase/include/QtCore/qhash.h \
		../../../src/qtbase/src/corelib/tools/qhash.h \
		../../../src/qtbase/include/QtCore/qsharedpointer_impl.h \
		../../../src/qtbase/src/corelib/tools/qsharedpointer_impl.h \
		../../../src/qtbase/include/QtGui/qfont.h \
		../../../src/qtbase/src/gui/text/qfont.h \
		../../../src/qtbase/include/QtGui/qfontmetrics.h \
		../../../src/qtbase/src/gui/text/qfontmetrics.h \
		../../../src/qtbase/include/QtGui/qfontinfo.h \
		../../../src/qtbase/src/gui/text/qfontinfo.h \
		../../../src/qtbase/include/QtWidgets/qsizepolicy.h \
		../../../src/qtbase/src/widgets/kernel/qsizepolicy.h \
		../../../src/qtbase/include/QtGui/qkeysequence.h \
		../../../src/qtbase/src/gui/kernel/qkeysequence.h \
		../../../src/qtbase/include/QtGui/qevent.h \
		../../../src/qtbase/src/gui/kernel/qevent.h \
		../../../src/qtbase/include/QtCore/qvariant.h \
		../../../src/qtbase/src/corelib/kernel/qvariant.h \
		../../../src/qtbase/include/QtCore/qmap.h \
		../../../src/qtbase/src/corelib/tools/qmap.h \
		../../../src/qtbase/include/QtCore/qdebug.h \
		../../../src/qtbase/src/corelib/io/qdebug.h \
		../../../src/qtbase/include/QtCore/qtextstream.h \
		../../../src/qtbase/src/corelib/io/qtextstream.h \
		../../../src/qtbase/include/QtCore/qlocale.h \
		../../../src/qtbase/src/corelib/tools/qlocale.h \
		../../../src/qtbase/include/QtCore/qset.h \
		../../../src/qtbase/src/corelib/tools/qset.h \
		../../../src/qtbase/include/QtCore/qcontiguouscache.h \
		../../../src/qtbase/src/corelib/tools/qcontiguouscache.h \
		../../../src/qtbase/include/QtCore/qurl.h \
		../../../src/qtbase/src/corelib/io/qurl.h \
		../../../src/qtbase/include/QtCore/qurlquery.h \
		../../../src/qtbase/src/corelib/io/qurlquery.h \
		../../../src/qtbase/include/QtCore/qfile.h \
		../../../src/qtbase/src/corelib/io/qfile.h \
		../../../src/qtbase/include/QtCore/qfiledevice.h \
		../../../src/qtbase/src/corelib/io/qfiledevice.h \
		../../../src/qtbase/include/QtGui/qvector2d.h \
		../../../src/qtbase/src/gui/math3d/qvector2d.h \
		../../../src/qtbase/include/QtGui/qtouchdevice.h \
		../../../src/qtbase/src/gui/kernel/qtouchdevice.h \
		../../../src/qtbase/include/QtGui/qguiapplication.h \
		../../../src/qtbase/src/gui/kernel/qguiapplication.h \
		../../../src/qtbase/include/QtGui/qinputmethod.h \
		../../../src/qtbase/src/gui/kernel/qinputmethod.h \
		../../../src/qtbase/include/QtWidgets/QPushButton \
		../../../src/qtbase/include/QtWidgets/qpushbutton.h \
		../../../src/qtbase/src/widgets/widgets/qpushbutton.h \
		../../../src/qtbase/include/QtWidgets/qabstractbutton.h \
		../../../src/qtbase/src/widgets/widgets/qabstractbutton.h \
		../../../src/qtbase/include/QtGui/qicon.h \
		../../../src/qtbase/src/gui/image/qicon.h \
		main_window.h \
		../../../src/qtbase/include/QtWidgets/QMainWindow \
		../../../src/qtbase/include/QtWidgets/qmainwindow.h \
		../../../src/qtbase/src/widgets/widgets/qmainwindow.h \
		../../../src/qtbase/include/QtWidgets/qtabwidget.h \
		../../../src/qtbase/src/widgets/widgets/qtabwidget.h \
		model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

main_window.o: main_window.cpp ../../../src/qtbase/include/QtWidgets/QtWidgets \
		../../../src/qtbase/include/QtWidgets/QtWidgetsDepends \
		../../../src/qtbase/include/QtCore/QtCore \
		../../../src/qtbase/include/QtCore/QtCoreDepends \
		../../../src/qtbase/include/QtCore/qabstractanimation.h \
		../../../src/qtbase/src/corelib/animation/qabstractanimation.h \
		../../../src/qtbase/include/QtCore/qobject.h \
		../../../src/qtbase/src/corelib/kernel/qobject.h \
		../../../src/qtbase/include/QtCore/qobjectdefs.h \
		../../../src/qtbase/src/corelib/kernel/qobjectdefs.h \
		../../../src/qtbase/include/QtCore/qnamespace.h \
		../../../src/qtbase/src/corelib/global/qnamespace.h \
		../../../src/qtbase/include/QtCore/qglobal.h \
		../../../src/qtbase/src/corelib/global/qglobal.h \
		../../../src/qtbase/include/QtCore/qconfig.h \
		../../../src/qtbase/src/corelib/global/qconfig.h \
		../../../src/qtbase/include/QtCore/qfeatures.h \
		../../../src/qtbase/src/corelib/global/qfeatures.h \
		../../../src/qtbase/include/QtCore/qsystemdetection.h \
		../../../src/qtbase/src/corelib/global/qsystemdetection.h \
		../../../src/qtbase/include/QtCore/qprocessordetection.h \
		../../../src/qtbase/src/corelib/global/qprocessordetection.h \
		../../../src/qtbase/include/QtCore/qcompilerdetection.h \
		../../../src/qtbase/src/corelib/global/qcompilerdetection.h \
		../../../src/qtbase/include/QtCore/qtypeinfo.h \
		../../../src/qtbase/src/corelib/global/qtypeinfo.h \
		../../../src/qtbase/include/QtCore/qtypetraits.h \
		../../../src/qtbase/src/corelib/global/qtypetraits.h \
		../../../src/qtbase/include/QtCore/qisenum.h \
		../../../src/qtbase/src/corelib/global/qisenum.h \
		../../../src/qtbase/include/QtCore/qsysinfo.h \
		../../../src/qtbase/src/corelib/global/qsysinfo.h \
		../../../src/qtbase/include/QtCore/qlogging.h \
		../../../src/qtbase/src/corelib/global/qlogging.h \
		../../../src/qtbase/include/QtCore/qflags.h \
		../../../src/qtbase/src/corelib/global/qflags.h \
		../../../src/qtbase/include/QtCore/qatomic.h \
		../../../src/qtbase/src/corelib/thread/qatomic.h \
		../../../src/qtbase/include/QtCore/qbasicatomic.h \
		../../../src/qtbase/src/corelib/thread/qbasicatomic.h \
		../../../src/qtbase/include/QtCore/qatomic_bootstrap.h \
		../../../src/qtbase/src/corelib/arch/qatomic_bootstrap.h \
		../../../src/qtbase/include/QtCore/qgenericatomic.h \
		../../../src/qtbase/src/corelib/thread/qgenericatomic.h \
		../../../src/qtbase/include/QtCore/qatomic_cxx11.h \
		../../../src/qtbase/src/corelib/arch/qatomic_cxx11.h \
		../../../src/qtbase/include/QtCore/qatomic_gcc.h \
		../../../src/qtbase/src/corelib/arch/qatomic_gcc.h \
		../../../src/qtbase/include/QtCore/qatomic_msvc.h \
		../../../src/qtbase/src/corelib/arch/qatomic_msvc.h \
		../../../src/qtbase/include/QtCore/qatomic_armv7.h \
		../../../src/qtbase/src/corelib/arch/qatomic_armv7.h \
		../../../src/qtbase/include/QtCore/qatomic_armv6.h \
		../../../src/qtbase/src/corelib/arch/qatomic_armv6.h \
		../../../src/qtbase/include/QtCore/qatomic_armv5.h \
		../../../src/qtbase/src/corelib/arch/qatomic_armv5.h \
		../../../src/qtbase/include/QtCore/qatomic_ia64.h \
		../../../src/qtbase/src/corelib/arch/qatomic_ia64.h \
		../../../src/qtbase/include/QtCore/qatomic_x86.h \
		../../../src/qtbase/src/corelib/arch/qatomic_x86.h \
		../../../src/qtbase/include/QtCore/qatomic_unix.h \
		../../../src/qtbase/src/corelib/arch/qatomic_unix.h \
		../../../src/qtbase/include/QtCore/qglobalstatic.h \
		../../../src/qtbase/src/corelib/global/qglobalstatic.h \
		../../../src/qtbase/include/QtCore/qmutex.h \
		../../../src/qtbase/src/corelib/thread/qmutex.h \
		../../../src/qtbase/include/QtCore/qnumeric.h \
		../../../src/qtbase/src/corelib/global/qnumeric.h \
		../../../src/qtbase/include/QtCore/qversiontagging.h \
		../../../src/qtbase/src/corelib/global/qversiontagging.h \
		../../../src/qtbase/include/QtCore/qobjectdefs_impl.h \
		../../../src/qtbase/src/corelib/kernel/qobjectdefs_impl.h \
		../../../src/qtbase/include/QtCore/qstring.h \
		../../../src/qtbase/src/corelib/tools/qstring.h \
		../../../src/qtbase/include/QtCore/qchar.h \
		../../../src/qtbase/src/corelib/tools/qchar.h \
		../../../src/qtbase/include/QtCore/qbytearray.h \
		../../../src/qtbase/src/corelib/tools/qbytearray.h \
		../../../src/qtbase/include/QtCore/qrefcount.h \
		../../../src/qtbase/src/corelib/tools/qrefcount.h \
		../../../src/qtbase/include/QtCore/qarraydata.h \
		../../../src/qtbase/src/corelib/tools/qarraydata.h \
		../../../src/qtbase/include/QtCore/qstringbuilder.h \
		../../../src/qtbase/src/corelib/tools/qstringbuilder.h \
		../../../src/qtbase/include/QtCore/qlist.h \
		../../../src/qtbase/src/corelib/tools/qlist.h \
		../../../src/qtbase/include/QtCore/qalgorithms.h \
		../../../src/qtbase/src/corelib/tools/qalgorithms.h \
		../../../src/qtbase/include/QtCore/qiterator.h \
		../../../src/qtbase/src/corelib/tools/qiterator.h \
		../../../src/qtbase/include/QtCore/qhashfunctions.h \
		../../../src/qtbase/src/corelib/tools/qhashfunctions.h \
		../../../src/qtbase/include/QtCore/qpair.h \
		../../../src/qtbase/src/corelib/tools/qpair.h \
		../../../src/qtbase/include/QtCore/qbytearraylist.h \
		../../../src/qtbase/src/corelib/tools/qbytearraylist.h \
		../../../src/qtbase/include/QtCore/qstringlist.h \
		../../../src/qtbase/src/corelib/tools/qstringlist.h \
		../../../src/qtbase/include/QtCore/qregexp.h \
		../../../src/qtbase/src/corelib/tools/qregexp.h \
		../../../src/qtbase/include/QtCore/qstringmatcher.h \
		../../../src/qtbase/src/corelib/tools/qstringmatcher.h \
		../../../src/qtbase/include/QtCore/qcoreevent.h \
		../../../src/qtbase/src/corelib/kernel/qcoreevent.h \
		../../../src/qtbase/include/QtCore/qscopedpointer.h \
		../../../src/qtbase/src/corelib/tools/qscopedpointer.h \
		../../../src/qtbase/include/QtCore/qmetatype.h \
		../../../src/qtbase/src/corelib/kernel/qmetatype.h \
		../../../src/qtbase/include/QtCore/qvarlengtharray.h \
		../../../src/qtbase/src/corelib/tools/qvarlengtharray.h \
		../../../src/qtbase/include/QtCore/qcontainerfwd.h \
		../../../src/qtbase/src/corelib/tools/qcontainerfwd.h \
		../../../src/qtbase/include/QtCore/qobject_impl.h \
		../../../src/qtbase/src/corelib/kernel/qobject_impl.h \
		../../../src/qtbase/include/QtCore/qanimationgroup.h \
		../../../src/qtbase/src/corelib/animation/qanimationgroup.h \
		../../../src/qtbase/include/QtCore/qparallelanimationgroup.h \
		../../../src/qtbase/src/corelib/animation/qparallelanimationgroup.h \
		../../../src/qtbase/include/QtCore/qpauseanimation.h \
		../../../src/qtbase/src/corelib/animation/qpauseanimation.h \
		../../../src/qtbase/include/QtCore/qpropertyanimation.h \
		../../../src/qtbase/src/corelib/animation/qpropertyanimation.h \
		../../../src/qtbase/include/QtCore/qvariantanimation.h \
		../../../src/qtbase/src/corelib/animation/qvariantanimation.h \
		../../../src/qtbase/include/QtCore/qeasingcurve.h \
		../../../src/qtbase/src/corelib/tools/qeasingcurve.h \
		../../../src/qtbase/include/QtCore/qvector.h \
		../../../src/qtbase/src/corelib/tools/qvector.h \
		../../../src/qtbase/include/QtCore/qpoint.h \
		../../../src/qtbase/src/corelib/tools/qpoint.h \
		../../../src/qtbase/include/QtCore/qvariant.h \
		../../../src/qtbase/src/corelib/kernel/qvariant.h \
		../../../src/qtbase/include/QtCore/qmap.h \
		../../../src/qtbase/src/corelib/tools/qmap.h \
		../../../src/qtbase/include/QtCore/qdebug.h \
		../../../src/qtbase/src/corelib/io/qdebug.h \
		../../../src/qtbase/include/QtCore/qhash.h \
		../../../src/qtbase/src/corelib/tools/qhash.h \
		../../../src/qtbase/include/QtCore/qtextstream.h \
		../../../src/qtbase/src/corelib/io/qtextstream.h \
		../../../src/qtbase/include/QtCore/qiodevice.h \
		../../../src/qtbase/src/corelib/io/qiodevice.h \
		../../../src/qtbase/include/QtCore/qlocale.h \
		../../../src/qtbase/src/corelib/tools/qlocale.h \
		../../../src/qtbase/include/QtCore/qshareddata.h \
		../../../src/qtbase/src/corelib/tools/qshareddata.h \
		../../../src/qtbase/include/QtCore/qset.h \
		../../../src/qtbase/src/corelib/tools/qset.h \
		../../../src/qtbase/include/QtCore/qcontiguouscache.h \
		../../../src/qtbase/src/corelib/tools/qcontiguouscache.h \
		../../../src/qtbase/include/QtCore/qsequentialanimationgroup.h \
		../../../src/qtbase/src/corelib/animation/qsequentialanimationgroup.h \
		../../../src/qtbase/include/QtCore/qtextcodec.h \
		../../../src/qtbase/src/corelib/codecs/qtextcodec.h \
		../../../src/qtbase/include/QtCore/qendian.h \
		../../../src/qtbase/src/corelib/global/qendian.h \
		../../../src/qtbase/include/QtCore/qlibraryinfo.h \
		../../../src/qtbase/src/corelib/global/qlibraryinfo.h \
		../../../src/qtbase/include/QtCore/qdatetime.h \
		../../../src/qtbase/src/corelib/tools/qdatetime.h \
		../../../src/qtbase/include/QtCore/qbuffer.h \
		../../../src/qtbase/src/corelib/io/qbuffer.h \
		../../../src/qtbase/include/QtCore/qdatastream.h \
		../../../src/qtbase/src/corelib/io/qdatastream.h \
		../../../src/qtbase/include/QtCore/qdir.h \
		../../../src/qtbase/src/corelib/io/qdir.h \
		../../../src/qtbase/include/QtCore/qfileinfo.h \
		../../../src/qtbase/src/corelib/io/qfileinfo.h \
		../../../src/qtbase/include/QtCore/qfile.h \
		../../../src/qtbase/src/corelib/io/qfile.h \
		../../../src/qtbase/include/QtCore/qfiledevice.h \
		../../../src/qtbase/src/corelib/io/qfiledevice.h \
		../../../src/qtbase/include/QtCore/qdiriterator.h \
		../../../src/qtbase/src/corelib/io/qdiriterator.h \
		../../../src/qtbase/include/QtCore/qfileselector.h \
		../../../src/qtbase/src/corelib/io/qfileselector.h \
		../../../src/qtbase/include/QtCore/QObject \
		../../../src/qtbase/include/QtCore/QStringList \
		../../../src/qtbase/include/QtCore/qfilesystemwatcher.h \
		../../../src/qtbase/src/corelib/io/qfilesystemwatcher.h \
		../../../src/qtbase/include/QtCore/qlockfile.h \
		../../../src/qtbase/src/corelib/io/qlockfile.h \
		../../../src/qtbase/include/QtCore/qloggingcategory.h \
		../../../src/qtbase/src/corelib/io/qloggingcategory.h \
		../../../src/qtbase/include/QtCore/qprocess.h \
		../../../src/qtbase/src/corelib/io/qprocess.h \
		../../../src/qtbase/include/QtCore/qresource.h \
		../../../src/qtbase/src/corelib/io/qresource.h \
		../../../src/qtbase/include/QtCore/qsavefile.h \
		../../../src/qtbase/src/corelib/io/qsavefile.h \
		../../../src/qtbase/include/QtCore/qsettings.h \
		../../../src/qtbase/src/corelib/io/qsettings.h \
		../../../src/qtbase/include/QtCore/qstandardpaths.h \
		../../../src/qtbase/src/corelib/io/qstandardpaths.h \
		../../../src/qtbase/include/QtCore/qstorageinfo.h \
		../../../src/qtbase/src/corelib/io/qstorageinfo.h \
		../../../src/qtbase/include/QtCore/qtemporarydir.h \
		../../../src/qtbase/src/corelib/io/qtemporarydir.h \
		../../../src/qtbase/include/QtCore/QScopedPointer \
		../../../src/qtbase/include/QtCore/qtemporaryfile.h \
		../../../src/qtbase/src/corelib/io/qtemporaryfile.h \
		../../../src/qtbase/include/QtCore/qurl.h \
		../../../src/qtbase/src/corelib/io/qurl.h \
		../../../src/qtbase/include/QtCore/qurlquery.h \
		../../../src/qtbase/src/corelib/io/qurlquery.h \
		../../../src/qtbase/include/QtCore/qabstractitemmodel.h \
		../../../src/qtbase/src/corelib/itemmodels/qabstractitemmodel.h \
		../../../src/qtbase/include/QtCore/qabstractproxymodel.h \
		../../../src/qtbase/src/corelib/itemmodels/qabstractproxymodel.h \
		../../../src/qtbase/include/QtCore/qidentityproxymodel.h \
		../../../src/qtbase/src/corelib/itemmodels/qidentityproxymodel.h \
		../../../src/qtbase/include/QtCore/qitemselectionmodel.h \
		../../../src/qtbase/src/corelib/itemmodels/qitemselectionmodel.h \
		../../../src/qtbase/include/QtCore/qsortfilterproxymodel.h \
		../../../src/qtbase/src/corelib/itemmodels/qsortfilterproxymodel.h \
		../../../src/qtbase/include/QtCore/qstringlistmodel.h \
		../../../src/qtbase/src/corelib/itemmodels/qstringlistmodel.h \
		../../../src/qtbase/include/QtCore/qjsonarray.h \
		../../../src/qtbase/src/corelib/json/qjsonarray.h \
		../../../src/qtbase/include/QtCore/qjsonvalue.h \
		../../../src/qtbase/src/corelib/json/qjsonvalue.h \
		../../../src/qtbase/include/QtCore/qjsondocument.h \
		../../../src/qtbase/src/corelib/json/qjsondocument.h \
		../../../src/qtbase/include/QtCore/qjsonobject.h \
		../../../src/qtbase/src/corelib/json/qjsonobject.h \
		../../../src/qtbase/include/QtCore/qabstracteventdispatcher.h \
		../../../src/qtbase/src/corelib/kernel/qabstracteventdispatcher.h \
		../../../src/qtbase/include/QtCore/qeventloop.h \
		../../../src/qtbase/src/corelib/kernel/qeventloop.h \
		../../../src/qtbase/include/QtCore/qabstractnativeeventfilter.h \
		../../../src/qtbase/src/corelib/kernel/qabstractnativeeventfilter.h \
		../../../src/qtbase/include/QtCore/qbasictimer.h \
		../../../src/qtbase/src/corelib/kernel/qbasictimer.h \
		../../../src/qtbase/include/QtCore/qcoreapplication.h \
		../../../src/qtbase/src/corelib/kernel/qcoreapplication.h \
		../../../src/qtbase/include/QtCore/qmath.h \
		../../../src/qtbase/src/corelib/kernel/qmath.h \
		../../../src/qtbase/include/QtCore/qmetaobject.h \
		../../../src/qtbase/src/corelib/kernel/qmetaobject.h \
		../../../src/qtbase/include/QtCore/qmimedata.h \
		../../../src/qtbase/src/corelib/kernel/qmimedata.h \
		../../../src/qtbase/include/QtCore/qobjectcleanuphandler.h \
		../../../src/qtbase/src/corelib/kernel/qobjectcleanuphandler.h \
		../../../src/qtbase/include/QtCore/qpointer.h \
		../../../src/qtbase/src/corelib/kernel/qpointer.h \
		../../../src/qtbase/include/QtCore/qsharedpointer.h \
		../../../src/qtbase/src/corelib/tools/qsharedpointer.h \
		../../../src/qtbase/include/QtCore/qsharedpointer_impl.h \
		../../../src/qtbase/src/corelib/tools/qsharedpointer_impl.h \
		../../../src/qtbase/include/QtCore/qsharedmemory.h \
		../../../src/qtbase/src/corelib/kernel/qsharedmemory.h \
		../../../src/qtbase/include/QtCore/qsignalmapper.h \
		../../../src/qtbase/src/corelib/kernel/qsignalmapper.h \
		../../../src/qtbase/include/QtCore/qsocketnotifier.h \
		../../../src/qtbase/src/corelib/kernel/qsocketnotifier.h \
		../../../src/qtbase/include/QtCore/qsystemsemaphore.h \
		../../../src/qtbase/src/corelib/kernel/qsystemsemaphore.h \
		../../../src/qtbase/include/QtCore/qtimer.h \
		../../../src/qtbase/src/corelib/kernel/qtimer.h \
		../../../src/qtbase/include/QtCore/qtranslator.h \
		../../../src/qtbase/src/corelib/kernel/qtranslator.h \
		../../../src/qtbase/include/QtCore/qwineventnotifier.h \
		../../../src/qtbase/src/corelib/kernel/qwineventnotifier.h \
		../../../src/qtbase/include/QtCore/qmimedatabase.h \
		../../../src/qtbase/src/corelib/mimetypes/qmimedatabase.h \
		../../../src/qtbase/include/QtCore/qmimetype.h \
		../../../src/qtbase/src/corelib/mimetypes/qmimetype.h \
		../../../src/qtbase/include/QtCore/qfactoryinterface.h \
		../../../src/qtbase/src/corelib/plugin/qfactoryinterface.h \
		../../../src/qtbase/include/QtCore/qlibrary.h \
		../../../src/qtbase/src/corelib/plugin/qlibrary.h \
		../../../src/qtbase/include/QtCore/qplugin.h \
		../../../src/qtbase/src/corelib/plugin/qplugin.h \
		../../../src/qtbase/include/QtCore/qpluginloader.h \
		../../../src/qtbase/src/corelib/plugin/qpluginloader.h \
		../../../src/qtbase/include/QtCore/quuid.h \
		../../../src/qtbase/src/corelib/plugin/quuid.h \
		../../../src/qtbase/include/QtCore/qabstractstate.h \
		../../../src/qtbase/src/corelib/statemachine/qabstractstate.h \
		../../../src/qtbase/include/QtCore/qabstracttransition.h \
		../../../src/qtbase/src/corelib/statemachine/qabstracttransition.h \
		../../../src/qtbase/include/QtCore/qeventtransition.h \
		../../../src/qtbase/src/corelib/statemachine/qeventtransition.h \
		../../../src/qtbase/include/QtCore/qfinalstate.h \
		../../../src/qtbase/src/corelib/statemachine/qfinalstate.h \
		../../../src/qtbase/include/QtCore/qhistorystate.h \
		../../../src/qtbase/src/corelib/statemachine/qhistorystate.h \
		../../../src/qtbase/include/QtCore/qsignaltransition.h \
		../../../src/qtbase/src/corelib/statemachine/qsignaltransition.h \
		../../../src/qtbase/include/QtCore/qstate.h \
		../../../src/qtbase/src/corelib/statemachine/qstate.h \
		../../../src/qtbase/include/QtCore/qstatemachine.h \
		../../../src/qtbase/src/corelib/statemachine/qstatemachine.h \
		../../../src/qtbase/include/QtCore/qexception.h \
		../../../src/qtbase/src/corelib/thread/qexception.h \
		../../../src/qtbase/include/QtCore/qfuture.h \
		../../../src/qtbase/src/corelib/thread/qfuture.h \
		../../../src/qtbase/include/QtCore/qfutureinterface.h \
		../../../src/qtbase/src/corelib/thread/qfutureinterface.h \
		../../../src/qtbase/include/QtCore/qrunnable.h \
		../../../src/qtbase/src/corelib/thread/qrunnable.h \
		../../../src/qtbase/include/QtCore/qresultstore.h \
		../../../src/qtbase/src/corelib/thread/qresultstore.h \
		../../../src/qtbase/include/QtCore/qfuturesynchronizer.h \
		../../../src/qtbase/src/corelib/thread/qfuturesynchronizer.h \
		../../../src/qtbase/include/QtCore/qfuturewatcher.h \
		../../../src/qtbase/src/corelib/thread/qfuturewatcher.h \
		../../../src/qtbase/include/QtCore/qreadwritelock.h \
		../../../src/qtbase/src/corelib/thread/qreadwritelock.h \
		../../../src/qtbase/include/QtCore/qsemaphore.h \
		../../../src/qtbase/src/corelib/thread/qsemaphore.h \
		../../../src/qtbase/include/QtCore/qthread.h \
		../../../src/qtbase/src/corelib/thread/qthread.h \
		../../../src/qtbase/include/QtCore/qthreadpool.h \
		../../../src/qtbase/src/corelib/thread/qthreadpool.h \
		../../../src/qtbase/include/QtCore/qthreadstorage.h \
		../../../src/qtbase/src/corelib/thread/qthreadstorage.h \
		../../../src/qtbase/include/QtCore/qwaitcondition.h \
		../../../src/qtbase/src/corelib/thread/qwaitcondition.h \
		../../../src/qtbase/include/QtCore/qarraydataops.h \
		../../../src/qtbase/src/corelib/tools/qarraydataops.h \
		../../../src/qtbase/include/QtCore/qarraydatapointer.h \
		../../../src/qtbase/src/corelib/tools/qarraydatapointer.h \
		../../../src/qtbase/include/QtCore/qbitarray.h \
		../../../src/qtbase/src/corelib/tools/qbitarray.h \
		../../../src/qtbase/include/QtCore/qbytearraymatcher.h \
		../../../src/qtbase/src/corelib/tools/qbytearraymatcher.h \
		../../../src/qtbase/include/QtCore/qcache.h \
		../../../src/qtbase/src/corelib/tools/qcache.h \
		../../../src/qtbase/include/QtCore/qcollator.h \
		../../../src/qtbase/src/corelib/tools/qcollator.h \
		../../../src/qtbase/include/QtCore/qcommandlineoption.h \
		../../../src/qtbase/src/corelib/tools/qcommandlineoption.h \
		../../../src/qtbase/include/QtCore/qcommandlineparser.h \
		../../../src/qtbase/src/corelib/tools/qcommandlineparser.h \
		../../../src/qtbase/include/QtCore/qcryptographichash.h \
		../../../src/qtbase/src/corelib/tools/qcryptographichash.h \
		../../../src/qtbase/include/QtCore/qelapsedtimer.h \
		../../../src/qtbase/src/corelib/tools/qelapsedtimer.h \
		../../../src/qtbase/include/QtCore/qline.h \
		../../../src/qtbase/src/corelib/tools/qline.h \
		../../../src/qtbase/include/QtCore/qlinkedlist.h \
		../../../src/qtbase/src/corelib/tools/qlinkedlist.h \
		../../../src/qtbase/include/QtCore/qmargins.h \
		../../../src/qtbase/src/corelib/tools/qmargins.h \
		../../../src/qtbase/include/QtCore/qmessageauthenticationcode.h \
		../../../src/qtbase/src/corelib/tools/qmessageauthenticationcode.h \
		../../../src/qtbase/include/QtCore/qqueue.h \
		../../../src/qtbase/src/corelib/tools/qqueue.h \
		../../../src/qtbase/include/QtCore/qrect.h \
		../../../src/qtbase/src/corelib/tools/qrect.h \
		../../../src/qtbase/include/QtCore/qsize.h \
		../../../src/qtbase/src/corelib/tools/qsize.h \
		../../../src/qtbase/include/QtCore/qregularexpression.h \
		../../../src/qtbase/src/corelib/tools/qregularexpression.h \
		../../../src/qtbase/include/QtCore/qscopedvaluerollback.h \
		../../../src/qtbase/src/corelib/tools/qscopedvaluerollback.h \
		../../../src/qtbase/include/QtCore/qstack.h \
		../../../src/qtbase/src/corelib/tools/qstack.h \
		../../../src/qtbase/include/QtCore/qtextboundaryfinder.h \
		../../../src/qtbase/src/corelib/tools/qtextboundaryfinder.h \
		../../../src/qtbase/include/QtCore/qtimeline.h \
		../../../src/qtbase/src/corelib/tools/qtimeline.h \
		../../../src/qtbase/include/QtCore/qtimezone.h \
		../../../src/qtbase/src/corelib/tools/qtimezone.h \
		../../../src/qtbase/include/QtCore/qversionnumber.h \
		../../../src/qtbase/src/corelib/tools/qversionnumber.h \
		../../../src/qtbase/include/QtCore/qxmlstream.h \
		../../../src/qtbase/src/corelib/xml/qxmlstream.h \
		../../../src/qtbase/include/QtCore/qtcoreversion.h \
		../../../src/qtbase/include/QtGui/QtGui \
		../../../src/qtbase/include/QtGui/QtGuiDepends \
		../../../src/qtbase/include/QtGui/qaccessible.h \
		../../../src/qtbase/src/gui/accessible/qaccessible.h \
		../../../src/qtbase/include/QtGui/qcolor.h \
		../../../src/qtbase/src/gui/painting/qcolor.h \
		../../../src/qtbase/include/QtGui/qrgb.h \
		../../../src/qtbase/src/gui/painting/qrgb.h \
		../../../src/qtbase/include/QtGui/qrgba64.h \
		../../../src/qtbase/src/gui/painting/qrgba64.h \
		../../../src/qtbase/include/QtGui/qevent.h \
		../../../src/qtbase/src/gui/kernel/qevent.h \
		../../../src/qtbase/include/QtGui/qwindowdefs.h \
		../../../src/qtbase/src/gui/kernel/qwindowdefs.h \
		../../../src/qtbase/include/QtGui/qwindowdefs_win.h \
		../../../src/qtbase/src/gui/kernel/qwindowdefs_win.h \
		../../../src/qtbase/include/QtGui/qregion.h \
		../../../src/qtbase/src/gui/painting/qregion.h \
		../../../src/qtbase/include/QtGui/qkeysequence.h \
		../../../src/qtbase/src/gui/kernel/qkeysequence.h \
		../../../src/qtbase/include/QtGui/qvector2d.h \
		../../../src/qtbase/src/gui/math3d/qvector2d.h \
		../../../src/qtbase/include/QtGui/qtouchdevice.h \
		../../../src/qtbase/src/gui/kernel/qtouchdevice.h \
		../../../src/qtbase/include/QtGui/qaccessiblebridge.h \
		../../../src/qtbase/src/gui/accessible/qaccessiblebridge.h \
		../../../src/qtbase/include/QtGui/qaccessibleobject.h \
		../../../src/qtbase/src/gui/accessible/qaccessibleobject.h \
		../../../src/qtbase/include/QtGui/qaccessibleplugin.h \
		../../../src/qtbase/src/gui/accessible/qaccessibleplugin.h \
		../../../src/qtbase/include/QtGui/qbitmap.h \
		../../../src/qtbase/src/gui/image/qbitmap.h \
		../../../src/qtbase/include/QtGui/qpixmap.h \
		../../../src/qtbase/src/gui/image/qpixmap.h \
		../../../src/qtbase/include/QtGui/qpaintdevice.h \
		../../../src/qtbase/src/gui/painting/qpaintdevice.h \
		../../../src/qtbase/include/QtGui/qimage.h \
		../../../src/qtbase/src/gui/image/qimage.h \
		../../../src/qtbase/include/QtGui/qpixelformat.h \
		../../../src/qtbase/src/gui/kernel/qpixelformat.h \
		../../../src/qtbase/include/QtGui/qtransform.h \
		../../../src/qtbase/src/gui/painting/qtransform.h \
		../../../src/qtbase/include/QtGui/qmatrix.h \
		../../../src/qtbase/src/gui/painting/qmatrix.h \
		../../../src/qtbase/include/QtGui/qpolygon.h \
		../../../src/qtbase/src/gui/painting/qpolygon.h \
		../../../src/qtbase/include/QtGui/qpainterpath.h \
		../../../src/qtbase/src/gui/painting/qpainterpath.h \
		../../../src/qtbase/include/QtGui/qicon.h \
		../../../src/qtbase/src/gui/image/qicon.h \
		../../../src/qtbase/include/QtGui/qiconengine.h \
		../../../src/qtbase/src/gui/image/qiconengine.h \
		../../../src/qtbase/include/QtGui/qiconengineplugin.h \
		../../../src/qtbase/src/gui/image/qiconengineplugin.h \
		../../../src/qtbase/include/QtGui/qimageiohandler.h \
		../../../src/qtbase/src/gui/image/qimageiohandler.h \
		../../../src/qtbase/include/QtGui/qimagereader.h \
		../../../src/qtbase/src/gui/image/qimagereader.h \
		../../../src/qtbase/include/QtGui/qimagewriter.h \
		../../../src/qtbase/src/gui/image/qimagewriter.h \
		../../../src/qtbase/include/QtGui/qmovie.h \
		../../../src/qtbase/src/gui/image/qmovie.h \
		../../../src/qtbase/include/QtGui/qpicture.h \
		../../../src/qtbase/src/gui/image/qpicture.h \
		../../../src/qtbase/include/QtGui/qpictureformatplugin.h \
		../../../src/qtbase/src/gui/image/qpictureformatplugin.h \
		../../../src/qtbase/include/QtGui/qpixmapcache.h \
		../../../src/qtbase/src/gui/image/qpixmapcache.h \
		../../../src/qtbase/include/QtGui/qstandarditemmodel.h \
		../../../src/qtbase/src/gui/itemmodels/qstandarditemmodel.h \
		../../../src/qtbase/include/QtGui/qbrush.h \
		../../../src/qtbase/src/gui/painting/qbrush.h \
		../../../src/qtbase/include/QtGui/qfont.h \
		../../../src/qtbase/src/gui/text/qfont.h \
		../../../src/qtbase/include/QtGui/qclipboard.h \
		../../../src/qtbase/src/gui/kernel/qclipboard.h \
		../../../src/qtbase/include/QtGui/qcursor.h \
		../../../src/qtbase/src/gui/kernel/qcursor.h \
		../../../src/qtbase/include/QtGui/qdrag.h \
		../../../src/qtbase/src/gui/kernel/qdrag.h \
		../../../src/qtbase/include/QtGui/qgenericplugin.h \
		../../../src/qtbase/src/gui/kernel/qgenericplugin.h \
		../../../src/qtbase/include/QtGui/qgenericpluginfactory.h \
		../../../src/qtbase/src/gui/kernel/qgenericpluginfactory.h \
		../../../src/qtbase/include/QtGui/qguiapplication.h \
		../../../src/qtbase/src/gui/kernel/qguiapplication.h \
		../../../src/qtbase/include/QtGui/qinputmethod.h \
		../../../src/qtbase/src/gui/kernel/qinputmethod.h \
		../../../src/qtbase/include/QtGui/qoffscreensurface.h \
		../../../src/qtbase/src/gui/kernel/qoffscreensurface.h \
		../../../src/qtbase/include/QtGui/qsurface.h \
		../../../src/qtbase/src/gui/kernel/qsurface.h \
		../../../src/qtbase/include/QtGui/qsurfaceformat.h \
		../../../src/qtbase/src/gui/kernel/qsurfaceformat.h \
		../../../src/qtbase/include/QtGui/qopenglcontext.h \
		../../../src/qtbase/src/gui/kernel/qopenglcontext.h \
		../../../src/qtbase/include/QtGui/QSurfaceFormat \
		../../../src/qtbase/include/QtGui/qopengl.h \
		../../../src/qtbase/src/gui/opengl/qopengl.h \
		../../../src/qtbase/include/QtCore/qt_windows.h \
		../../../src/qtbase/src/corelib/global/qt_windows.h \
		../../../src/qtbase/include/QtGui/qopengles2ext.h \
		../../../src/qtbase/src/gui/opengl/qopengles2ext.h \
		../../../src/qtbase/include/QtGui/qopenglext.h \
		../../../src/qtbase/src/gui/opengl/qopenglext.h \
		../../../src/qtbase/include/QtGui/qopenglversionfunctions.h \
		../../../src/qtbase/src/gui/opengl/qopenglversionfunctions.h \
		../../../src/qtbase/include/QtGui/qopenglwindow.h \
		../../../src/qtbase/src/gui/kernel/qopenglwindow.h \
		../../../src/qtbase/include/QtGui/QPaintDeviceWindow \
		../../../src/qtbase/include/QtGui/qpaintdevicewindow.h \
		../../../src/qtbase/src/gui/kernel/qpaintdevicewindow.h \
		../../../src/qtbase/include/QtGui/QWindow \
		../../../src/qtbase/include/QtGui/qwindow.h \
		../../../src/qtbase/src/gui/kernel/qwindow.h \
		../../../src/qtbase/include/QtCore/QEvent \
		../../../src/qtbase/include/QtCore/QMargins \
		../../../src/qtbase/include/QtCore/QRect \
		../../../src/qtbase/include/QtGui/QPaintDevice \
		../../../src/qtbase/include/QtGui/QOpenGLContext \
		../../../src/qtbase/include/QtGui/QImage \
		../../../src/qtbase/include/QtGui/qpalette.h \
		../../../src/qtbase/src/gui/kernel/qpalette.h \
		../../../src/qtbase/include/QtGui/qrasterwindow.h \
		../../../src/qtbase/src/gui/kernel/qrasterwindow.h \
		../../../src/qtbase/include/QtGui/qscreen.h \
		../../../src/qtbase/src/gui/kernel/qscreen.h \
		../../../src/qtbase/include/QtCore/QList \
		../../../src/qtbase/include/QtCore/QSize \
		../../../src/qtbase/include/QtCore/QSizeF \
		../../../src/qtbase/include/QtGui/QTransform \
		../../../src/qtbase/include/QtGui/qsessionmanager.h \
		../../../src/qtbase/src/gui/kernel/qsessionmanager.h \
		../../../src/qtbase/include/QtGui/qstylehints.h \
		../../../src/qtbase/src/gui/kernel/qstylehints.h \
		../../../src/qtbase/include/QtGui/qgenericmatrix.h \
		../../../src/qtbase/src/gui/math3d/qgenericmatrix.h \
		../../../src/qtbase/include/QtGui/qmatrix4x4.h \
		../../../src/qtbase/src/gui/math3d/qmatrix4x4.h \
		../../../src/qtbase/include/QtGui/qvector3d.h \
		../../../src/qtbase/src/gui/math3d/qvector3d.h \
		../../../src/qtbase/include/QtGui/qvector4d.h \
		../../../src/qtbase/src/gui/math3d/qvector4d.h \
		../../../src/qtbase/include/QtGui/qquaternion.h \
		../../../src/qtbase/src/gui/math3d/qquaternion.h \
		../../../src/qtbase/include/QtGui/qopenglbuffer.h \
		../../../src/qtbase/src/gui/opengl/qopenglbuffer.h \
		../../../src/qtbase/include/QtGui/qopengldebug.h \
		../../../src/qtbase/src/gui/opengl/qopengldebug.h \
		../../../src/qtbase/include/QtGui/qopenglextrafunctions.h \
		../../../src/qtbase/src/gui/opengl/qopenglextrafunctions.h \
		../../../src/qtbase/include/QtGui/qopenglfunctions.h \
		../../../src/qtbase/src/gui/opengl/qopenglfunctions.h \
		../../../src/qtbase/include/QtGui/qopenglframebufferobject.h \
		../../../src/qtbase/src/gui/opengl/qopenglframebufferobject.h \
		../../../src/qtbase/include/QtGui/qopenglpaintdevice.h \
		../../../src/qtbase/src/gui/opengl/qopenglpaintdevice.h \
		../../../src/qtbase/include/QtGui/qopenglpixeltransferoptions.h \
		../../../src/qtbase/src/gui/opengl/qopenglpixeltransferoptions.h \
		../../../src/qtbase/include/QtCore/QSharedDataPointer \
		../../../src/qtbase/include/QtGui/qopenglshaderprogram.h \
		../../../src/qtbase/src/gui/opengl/qopenglshaderprogram.h \
		../../../src/qtbase/include/QtGui/qopengltexture.h \
		../../../src/qtbase/src/gui/opengl/qopengltexture.h \
		../../../src/qtbase/include/QtGui/qopengltimerquery.h \
		../../../src/qtbase/src/gui/opengl/qopengltimerquery.h \
		../../../src/qtbase/include/QtGui/qopenglvertexarrayobject.h \
		../../../src/qtbase/src/gui/opengl/qopenglvertexarrayobject.h \
		../../../src/qtbase/include/QtGui/qbackingstore.h \
		../../../src/qtbase/src/gui/painting/qbackingstore.h \
		../../../src/qtbase/include/QtGui/qpagedpaintdevice.h \
		../../../src/qtbase/src/gui/painting/qpagedpaintdevice.h \
		../../../src/qtbase/include/QtGui/qpagelayout.h \
		../../../src/qtbase/src/gui/painting/qpagelayout.h \
		../../../src/qtbase/include/QtGui/qpagesize.h \
		../../../src/qtbase/src/gui/painting/qpagesize.h \
		../../../src/qtbase/include/QtGui/qpaintengine.h \
		../../../src/qtbase/src/gui/painting/qpaintengine.h \
		../../../src/qtbase/include/QtGui/qpainter.h \
		../../../src/qtbase/src/gui/painting/qpainter.h \
		../../../src/qtbase/include/QtGui/qtextoption.h \
		../../../src/qtbase/src/gui/text/qtextoption.h \
		../../../src/qtbase/include/QtGui/qpen.h \
		../../../src/qtbase/src/gui/painting/qpen.h \
		../../../src/qtbase/include/QtGui/qfontinfo.h \
		../../../src/qtbase/src/gui/text/qfontinfo.h \
		../../../src/qtbase/include/QtGui/qfontmetrics.h \
		../../../src/qtbase/src/gui/text/qfontmetrics.h \
		../../../src/qtbase/include/QtGui/qpdfwriter.h \
		../../../src/qtbase/src/gui/painting/qpdfwriter.h \
		../../../src/qtbase/include/QtGui/qabstracttextdocumentlayout.h \
		../../../src/qtbase/src/gui/text/qabstracttextdocumentlayout.h \
		../../../src/qtbase/include/QtGui/qtextlayout.h \
		../../../src/qtbase/src/gui/text/qtextlayout.h \
		../../../src/qtbase/include/QtGui/qtextformat.h \
		../../../src/qtbase/src/gui/text/qtextformat.h \
		../../../src/qtbase/include/QtGui/qglyphrun.h \
		../../../src/qtbase/src/gui/text/qglyphrun.h \
		../../../src/qtbase/include/QtGui/qrawfont.h \
		../../../src/qtbase/src/gui/text/qrawfont.h \
		../../../src/qtbase/include/QtGui/qfontdatabase.h \
		../../../src/qtbase/src/gui/text/qfontdatabase.h \
		../../../src/qtbase/include/QtGui/qtextcursor.h \
		../../../src/qtbase/src/gui/text/qtextcursor.h \
		../../../src/qtbase/include/QtGui/qtextdocument.h \
		../../../src/qtbase/src/gui/text/qtextdocument.h \
		../../../src/qtbase/include/QtGui/qstatictext.h \
		../../../src/qtbase/src/gui/text/qstatictext.h \
		../../../src/qtbase/include/QtGui/qsyntaxhighlighter.h \
		../../../src/qtbase/src/gui/text/qsyntaxhighlighter.h \
		../../../src/qtbase/include/QtGui/qtextobject.h \
		../../../src/qtbase/src/gui/text/qtextobject.h \
		../../../src/qtbase/include/QtGui/qtextdocumentfragment.h \
		../../../src/qtbase/src/gui/text/qtextdocumentfragment.h \
		../../../src/qtbase/include/QtGui/qtextdocumentwriter.h \
		../../../src/qtbase/src/gui/text/qtextdocumentwriter.h \
		../../../src/qtbase/include/QtGui/qtextlist.h \
		../../../src/qtbase/src/gui/text/qtextlist.h \
		../../../src/qtbase/include/QtGui/qtexttable.h \
		../../../src/qtbase/src/gui/text/qtexttable.h \
		../../../src/qtbase/include/QtGui/qdesktopservices.h \
		../../../src/qtbase/src/gui/util/qdesktopservices.h \
		../../../src/qtbase/include/QtGui/qvalidator.h \
		../../../src/qtbase/src/gui/util/qvalidator.h \
		../../../src/qtbase/include/QtGui/qtguiversion.h \
		../../../src/qtbase/include/QtWidgets/qaccessiblewidget.h \
		../../../src/qtbase/src/widgets/accessible/qaccessiblewidget.h \
		../../../src/qtbase/include/QtWidgets/qcolordialog.h \
		../../../src/qtbase/src/widgets/dialogs/qcolordialog.h \
		../../../src/qtbase/include/QtWidgets/qdialog.h \
		../../../src/qtbase/src/widgets/dialogs/qdialog.h \
		../../../src/qtbase/include/QtWidgets/qwidget.h \
		../../../src/qtbase/src/widgets/kernel/qwidget.h \
		../../../src/qtbase/include/QtWidgets/qsizepolicy.h \
		../../../src/qtbase/src/widgets/kernel/qsizepolicy.h \
		../../../src/qtbase/include/QtWidgets/qerrormessage.h \
		../../../src/qtbase/src/widgets/dialogs/qerrormessage.h \
		../../../src/qtbase/include/QtWidgets/qfiledialog.h \
		../../../src/qtbase/src/widgets/dialogs/qfiledialog.h \
		../../../src/qtbase/include/QtWidgets/qfilesystemmodel.h \
		../../../src/qtbase/src/widgets/dialogs/qfilesystemmodel.h \
		../../../src/qtbase/include/QtWidgets/qfontdialog.h \
		../../../src/qtbase/src/widgets/dialogs/qfontdialog.h \
		../../../src/qtbase/include/QtWidgets/qinputdialog.h \
		../../../src/qtbase/src/widgets/dialogs/qinputdialog.h \
		../../../src/qtbase/include/QtWidgets/qlineedit.h \
		../../../src/qtbase/src/widgets/widgets/qlineedit.h \
		../../../src/qtbase/include/QtWidgets/qframe.h \
		../../../src/qtbase/src/widgets/widgets/qframe.h \
		../../../src/qtbase/include/QtWidgets/qmessagebox.h \
		../../../src/qtbase/src/widgets/dialogs/qmessagebox.h \
		../../../src/qtbase/include/QtWidgets/qprogressdialog.h \
		../../../src/qtbase/src/widgets/dialogs/qprogressdialog.h \
		../../../src/qtbase/include/QtWidgets/qwizard.h \
		../../../src/qtbase/src/widgets/dialogs/qwizard.h \
		../../../src/qtbase/include/QtWidgets/qgraphicseffect.h \
		../../../src/qtbase/src/widgets/effects/qgraphicseffect.h \
		../../../src/qtbase/include/QtWidgets/qgraphicsanchorlayout.h \
		../../../src/qtbase/src/widgets/graphicsview/qgraphicsanchorlayout.h \
		../../../src/qtbase/include/QtWidgets/qgraphicsitem.h \
		../../../src/qtbase/src/widgets/graphicsview/qgraphicsitem.h \
		../../../src/qtbase/include/QtWidgets/qgraphicslayout.h \
		../../../src/qtbase/src/widgets/graphicsview/qgraphicslayout.h \
		../../../src/qtbase/include/QtWidgets/qgraphicslayoutitem.h \
		../../../src/qtbase/src/widgets/graphicsview/qgraphicslayoutitem.h \
		../../../src/qtbase/include/QtWidgets/qgraphicsgridlayout.h \
		../../../src/qtbase/src/widgets/graphicsview/qgraphicsgridlayout.h \
		../../../src/qtbase/include/QtWidgets/qgraphicsitemanimation.h \
		../../../src/qtbase/src/widgets/graphicsview/qgraphicsitemanimation.h \
		../../../src/qtbase/include/QtWidgets/qgraphicslinearlayout.h \
		../../../src/qtbase/src/widgets/graphicsview/qgraphicslinearlayout.h \
		../../../src/qtbase/include/QtWidgets/qgraphicsproxywidget.h \
		../../../src/qtbase/src/widgets/graphicsview/qgraphicsproxywidget.h \
		../../../src/qtbase/include/QtWidgets/qgraphicswidget.h \
		../../../src/qtbase/src/widgets/graphicsview/qgraphicswidget.h \
		../../../src/qtbase/include/QtWidgets/qgraphicsscene.h \
		../../../src/qtbase/src/widgets/graphicsview/qgraphicsscene.h \
		../../../src/qtbase/include/QtWidgets/qgraphicssceneevent.h \
		../../../src/qtbase/src/widgets/graphicsview/qgraphicssceneevent.h \
		../../../src/qtbase/include/QtWidgets/qgraphicstransform.h \
		../../../src/qtbase/src/widgets/graphicsview/qgraphicstransform.h \
		../../../src/qtbase/include/QtGui/QVector3D \
		../../../src/qtbase/include/QtGui/QMatrix4x4 \
		../../../src/qtbase/include/QtWidgets/qgraphicsview.h \
		../../../src/qtbase/src/widgets/graphicsview/qgraphicsview.h \
		../../../src/qtbase/include/QtWidgets/qscrollarea.h \
		../../../src/qtbase/src/widgets/widgets/qscrollarea.h \
		../../../src/qtbase/include/QtWidgets/qabstractscrollarea.h \
		../../../src/qtbase/src/widgets/widgets/qabstractscrollarea.h \
		../../../src/qtbase/include/QtWidgets/qabstractitemdelegate.h \
		../../../src/qtbase/src/widgets/itemviews/qabstractitemdelegate.h \
		../../../src/qtbase/include/QtWidgets/qstyleoption.h \
		../../../src/qtbase/src/widgets/styles/qstyleoption.h \
		../../../src/qtbase/include/QtWidgets/qabstractspinbox.h \
		../../../src/qtbase/src/widgets/widgets/qabstractspinbox.h \
		../../../src/qtbase/include/QtWidgets/qslider.h \
		../../../src/qtbase/src/widgets/widgets/qslider.h \
		../../../src/qtbase/include/QtWidgets/qabstractslider.h \
		../../../src/qtbase/src/widgets/widgets/qabstractslider.h \
		../../../src/qtbase/include/QtWidgets/qstyle.h \
		../../../src/qtbase/src/widgets/styles/qstyle.h \
		../../../src/qtbase/include/QtWidgets/qtabbar.h \
		../../../src/qtbase/src/widgets/widgets/qtabbar.h \
		../../../src/qtbase/include/QtWidgets/qtabwidget.h \
		../../../src/qtbase/src/widgets/widgets/qtabwidget.h \
		../../../src/qtbase/include/QtWidgets/qrubberband.h \
		../../../src/qtbase/src/widgets/widgets/qrubberband.h \
		../../../src/qtbase/include/QtWidgets/qabstractitemview.h \
		../../../src/qtbase/src/widgets/itemviews/qabstractitemview.h \
		../../../src/qtbase/include/QtWidgets/qcolumnview.h \
		../../../src/qtbase/src/widgets/itemviews/qcolumnview.h \
		../../../src/qtbase/include/QtWidgets/qdatawidgetmapper.h \
		../../../src/qtbase/src/widgets/itemviews/qdatawidgetmapper.h \
		../../../src/qtbase/include/QtWidgets/qdirmodel.h \
		../../../src/qtbase/src/widgets/itemviews/qdirmodel.h \
		../../../src/qtbase/include/QtWidgets/qfileiconprovider.h \
		../../../src/qtbase/src/widgets/itemviews/qfileiconprovider.h \
		../../../src/qtbase/include/QtWidgets/qheaderview.h \
		../../../src/qtbase/src/widgets/itemviews/qheaderview.h \
		../../../src/qtbase/include/QtWidgets/qitemdelegate.h \
		../../../src/qtbase/src/widgets/itemviews/qitemdelegate.h \
		../../../src/qtbase/include/QtWidgets/qitemeditorfactory.h \
		../../../src/qtbase/src/widgets/itemviews/qitemeditorfactory.h \
		../../../src/qtbase/include/QtWidgets/qlistview.h \
		../../../src/qtbase/src/widgets/itemviews/qlistview.h \
		../../../src/qtbase/include/QtWidgets/qlistwidget.h \
		../../../src/qtbase/src/widgets/itemviews/qlistwidget.h \
		../../../src/qtbase/include/QtWidgets/qstyleditemdelegate.h \
		../../../src/qtbase/src/widgets/itemviews/qstyleditemdelegate.h \
		../../../src/qtbase/include/QtWidgets/qtableview.h \
		../../../src/qtbase/src/widgets/itemviews/qtableview.h \
		../../../src/qtbase/include/QtWidgets/qtablewidget.h \
		../../../src/qtbase/src/widgets/itemviews/qtablewidget.h \
		../../../src/qtbase/include/QtWidgets/qtreeview.h \
		../../../src/qtbase/src/widgets/itemviews/qtreeview.h \
		../../../src/qtbase/include/QtWidgets/qtreewidget.h \
		../../../src/qtbase/src/widgets/itemviews/qtreewidget.h \
		../../../src/qtbase/include/QtWidgets/qtreewidgetitemiterator.h \
		../../../src/qtbase/src/widgets/itemviews/qtreewidgetitemiterator.h \
		../../../src/qtbase/include/QtWidgets/qaction.h \
		../../../src/qtbase/src/widgets/kernel/qaction.h \
		../../../src/qtbase/include/QtWidgets/qactiongroup.h \
		../../../src/qtbase/src/widgets/kernel/qactiongroup.h \
		../../../src/qtbase/include/QtWidgets/qapplication.h \
		../../../src/qtbase/src/widgets/kernel/qapplication.h \
		../../../src/qtbase/include/QtWidgets/qdesktopwidget.h \
		../../../src/qtbase/src/widgets/kernel/qdesktopwidget.h \
		../../../src/qtbase/include/QtWidgets/qboxlayout.h \
		../../../src/qtbase/src/widgets/kernel/qboxlayout.h \
		../../../src/qtbase/include/QtWidgets/qlayout.h \
		../../../src/qtbase/src/widgets/kernel/qlayout.h \
		../../../src/qtbase/include/QtWidgets/qlayoutitem.h \
		../../../src/qtbase/src/widgets/kernel/qlayoutitem.h \
		../../../src/qtbase/include/QtWidgets/qgridlayout.h \
		../../../src/qtbase/src/widgets/kernel/qgridlayout.h \
		../../../src/qtbase/include/QtWidgets/qformlayout.h \
		../../../src/qtbase/src/widgets/kernel/qformlayout.h \
		../../../src/qtbase/include/QtWidgets/QLayout \
		../../../src/qtbase/include/QtWidgets/qgesture.h \
		../../../src/qtbase/src/widgets/kernel/qgesture.h \
		../../../src/qtbase/include/QtWidgets/qgesturerecognizer.h \
		../../../src/qtbase/src/widgets/kernel/qgesturerecognizer.h \
		../../../src/qtbase/include/QtWidgets/qopenglwidget.h \
		../../../src/qtbase/src/widgets/kernel/qopenglwidget.h \
		../../../src/qtbase/include/QtWidgets/QWidget \
		../../../src/qtbase/include/QtWidgets/qshortcut.h \
		../../../src/qtbase/src/widgets/kernel/qshortcut.h \
		../../../src/qtbase/include/QtWidgets/qstackedlayout.h \
		../../../src/qtbase/src/widgets/kernel/qstackedlayout.h \
		../../../src/qtbase/include/QtWidgets/qtooltip.h \
		../../../src/qtbase/src/widgets/kernel/qtooltip.h \
		../../../src/qtbase/include/QtWidgets/qwhatsthis.h \
		../../../src/qtbase/src/widgets/kernel/qwhatsthis.h \
		../../../src/qtbase/include/QtWidgets/qwidgetaction.h \
		../../../src/qtbase/src/widgets/kernel/qwidgetaction.h \
		../../../src/qtbase/include/QtWidgets/qkeyeventtransition.h \
		../../../src/qtbase/src/widgets/statemachine/qkeyeventtransition.h \
		../../../src/qtbase/include/QtWidgets/qmouseeventtransition.h \
		../../../src/qtbase/src/widgets/statemachine/qmouseeventtransition.h \
		../../../src/qtbase/include/QtWidgets/qcommonstyle.h \
		../../../src/qtbase/src/widgets/styles/qcommonstyle.h \
		../../../src/qtbase/include/QtWidgets/qdrawutil.h \
		../../../src/qtbase/src/widgets/styles/qdrawutil.h \
		../../../src/qtbase/include/QtWidgets/qproxystyle.h \
		../../../src/qtbase/src/widgets/styles/qproxystyle.h \
		../../../src/qtbase/include/QtWidgets/QCommonStyle \
		../../../src/qtbase/include/QtWidgets/qstylefactory.h \
		../../../src/qtbase/src/widgets/styles/qstylefactory.h \
		../../../src/qtbase/include/QtWidgets/qstylepainter.h \
		../../../src/qtbase/src/widgets/styles/qstylepainter.h \
		../../../src/qtbase/include/QtWidgets/qstyleplugin.h \
		../../../src/qtbase/src/widgets/styles/qstyleplugin.h \
		../../../src/qtbase/include/QtWidgets/qcolormap.h \
		../../../src/qtbase/src/widgets/util/qcolormap.h \
		../../../src/qtbase/include/QtWidgets/qcompleter.h \
		../../../src/qtbase/src/widgets/util/qcompleter.h \
		../../../src/qtbase/include/QtWidgets/qscroller.h \
		../../../src/qtbase/src/widgets/util/qscroller.h \
		../../../src/qtbase/include/QtCore/QPointF \
		../../../src/qtbase/include/QtWidgets/QScrollerProperties \
		../../../src/qtbase/include/QtWidgets/qscrollerproperties.h \
		../../../src/qtbase/src/widgets/util/qscrollerproperties.h \
		../../../src/qtbase/include/QtCore/QMetaType \
		../../../src/qtbase/include/QtCore/QVariant \
		../../../src/qtbase/include/QtWidgets/qsystemtrayicon.h \
		../../../src/qtbase/src/widgets/util/qsystemtrayicon.h \
		../../../src/qtbase/include/QtWidgets/qundogroup.h \
		../../../src/qtbase/src/widgets/util/qundogroup.h \
		../../../src/qtbase/include/QtWidgets/qundostack.h \
		../../../src/qtbase/src/widgets/util/qundostack.h \
		../../../src/qtbase/include/QtWidgets/qundoview.h \
		../../../src/qtbase/src/widgets/util/qundoview.h \
		../../../src/qtbase/include/QtWidgets/qabstractbutton.h \
		../../../src/qtbase/src/widgets/widgets/qabstractbutton.h \
		../../../src/qtbase/include/QtWidgets/qbuttongroup.h \
		../../../src/qtbase/src/widgets/widgets/qbuttongroup.h \
		../../../src/qtbase/include/QtWidgets/qcalendarwidget.h \
		../../../src/qtbase/src/widgets/widgets/qcalendarwidget.h \
		../../../src/qtbase/include/QtWidgets/qcheckbox.h \
		../../../src/qtbase/src/widgets/widgets/qcheckbox.h \
		../../../src/qtbase/include/QtWidgets/qcombobox.h \
		../../../src/qtbase/src/widgets/widgets/qcombobox.h \
		../../../src/qtbase/include/QtWidgets/qcommandlinkbutton.h \
		../../../src/qtbase/src/widgets/widgets/qcommandlinkbutton.h \
		../../../src/qtbase/include/QtWidgets/qpushbutton.h \
		../../../src/qtbase/src/widgets/widgets/qpushbutton.h \
		../../../src/qtbase/include/QtWidgets/qdatetimeedit.h \
		../../../src/qtbase/src/widgets/widgets/qdatetimeedit.h \
		../../../src/qtbase/include/QtWidgets/qdial.h \
		../../../src/qtbase/src/widgets/widgets/qdial.h \
		../../../src/qtbase/include/QtWidgets/qdialogbuttonbox.h \
		../../../src/qtbase/src/widgets/widgets/qdialogbuttonbox.h \
		../../../src/qtbase/include/QtWidgets/qdockwidget.h \
		../../../src/qtbase/src/widgets/widgets/qdockwidget.h \
		../../../src/qtbase/include/QtWidgets/qfocusframe.h \
		../../../src/qtbase/src/widgets/widgets/qfocusframe.h \
		../../../src/qtbase/include/QtWidgets/qfontcombobox.h \
		../../../src/qtbase/src/widgets/widgets/qfontcombobox.h \
		../../../src/qtbase/include/QtWidgets/qgroupbox.h \
		../../../src/qtbase/src/widgets/widgets/qgroupbox.h \
		../../../src/qtbase/include/QtWidgets/qkeysequenceedit.h \
		../../../src/qtbase/src/widgets/widgets/qkeysequenceedit.h \
		../../../src/qtbase/include/QtWidgets/qlabel.h \
		../../../src/qtbase/src/widgets/widgets/qlabel.h \
		../../../src/qtbase/include/QtWidgets/qlcdnumber.h \
		../../../src/qtbase/src/widgets/widgets/qlcdnumber.h \
		../../../src/qtbase/include/QtWidgets/qmainwindow.h \
		../../../src/qtbase/src/widgets/widgets/qmainwindow.h \
		../../../src/qtbase/include/QtWidgets/qmdiarea.h \
		../../../src/qtbase/src/widgets/widgets/qmdiarea.h \
		../../../src/qtbase/include/QtWidgets/qmdisubwindow.h \
		../../../src/qtbase/src/widgets/widgets/qmdisubwindow.h \
		../../../src/qtbase/include/QtWidgets/qmenu.h \
		../../../src/qtbase/src/widgets/widgets/qmenu.h \
		../../../src/qtbase/include/QtWidgets/qmenubar.h \
		../../../src/qtbase/src/widgets/widgets/qmenubar.h \
		../../../src/qtbase/include/QtWidgets/qplaintextedit.h \
		../../../src/qtbase/src/widgets/widgets/qplaintextedit.h \
		../../../src/qtbase/include/QtWidgets/qtextedit.h \
		../../../src/qtbase/src/widgets/widgets/qtextedit.h \
		../../../src/qtbase/include/QtWidgets/qprogressbar.h \
		../../../src/qtbase/src/widgets/widgets/qprogressbar.h \
		../../../src/qtbase/include/QtWidgets/qradiobutton.h \
		../../../src/qtbase/src/widgets/widgets/qradiobutton.h \
		../../../src/qtbase/include/QtWidgets/qscrollbar.h \
		../../../src/qtbase/src/widgets/widgets/qscrollbar.h \
		../../../src/qtbase/include/QtWidgets/qsizegrip.h \
		../../../src/qtbase/src/widgets/widgets/qsizegrip.h \
		../../../src/qtbase/include/QtWidgets/qspinbox.h \
		../../../src/qtbase/src/widgets/widgets/qspinbox.h \
		../../../src/qtbase/include/QtWidgets/qsplashscreen.h \
		../../../src/qtbase/src/widgets/widgets/qsplashscreen.h \
		../../../src/qtbase/include/QtWidgets/qsplitter.h \
		../../../src/qtbase/src/widgets/widgets/qsplitter.h \
		../../../src/qtbase/include/QtWidgets/qstackedwidget.h \
		../../../src/qtbase/src/widgets/widgets/qstackedwidget.h \
		../../../src/qtbase/include/QtWidgets/qstatusbar.h \
		../../../src/qtbase/src/widgets/widgets/qstatusbar.h \
		../../../src/qtbase/include/QtWidgets/qtextbrowser.h \
		../../../src/qtbase/src/widgets/widgets/qtextbrowser.h \
		../../../src/qtbase/include/QtWidgets/qtoolbar.h \
		../../../src/qtbase/src/widgets/widgets/qtoolbar.h \
		../../../src/qtbase/include/QtWidgets/qtoolbox.h \
		../../../src/qtbase/src/widgets/widgets/qtoolbox.h \
		../../../src/qtbase/include/QtWidgets/qtoolbutton.h \
		../../../src/qtbase/src/widgets/widgets/qtoolbutton.h \
		../../../src/qtbase/include/QtWidgets/qtwidgetsversion.h \
		main_window.h \
		../../../src/qtbase/include/QtWidgets/QMainWindow \
		model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_window.o main_window.cpp

model.o: model.cpp model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model.o model.cpp

qrc_app.o: qrc_app.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_app.o qrc_app.cpp

moc_main_window.o: moc_main_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main_window.o moc_main_window.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

